In [4]:
# all library and packages used in this notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Manipulation with Pandas

Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame. **DataFrames are essentially multidimensional arrays with attached row and column labels**, and often with heterogeneous types and/or missing data. 

As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

As we saw, NumPy’s ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks. **its limitations become clear when :**

1. when we need more flexibility (attaching labels to data, working with missing data, etc.)
2. when attempting operations that do not map well to element-wise broadcasting (groupings, pivots,etc.)

## Introducing Pandas Objects

### The Pandas Series Object

A Pandas Series is a **one-dimensional array** of indexed data. **It can be created from a list or array**

In [14]:
# pandas series object
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data.index
data.index.values # show values of pandas object

array([0, 1, 2, 3])

In [ ]:
"""
Like with a NumPy array, data can be accessed by the associated index via the familiar
Python square-bracket notation
"""
data[0] # output : np.float64(0.25)
data[:2]

0    0.25
1    0.50
dtype: float64

#### Series as generalized NumPy array

From what we’ve seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. 

The essential difference is the presence of the index: 

 - while the NumPy array has an implicitly defined integer index used
to access the values
- the Pandas Series has an explicitly defined index associated with the values

    - This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. **if we wish, we can use strings as an index**

In [29]:
# create pandas object with non integer as index

data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index = ('a','b','c','d'))

data.index.values # output : <StringArray>['a', 'b', 'c', 'd'] Length: 4, dtype: str
print(data)
print("--"*20)
# And the item access works as expected
data['b']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
----------------------------------------

np.float64(0.5)

#### Series as specialized dictionary

In this way, you can think of a Pandas Series a bit like a specialization of a Python dictionary. **A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values**

In [33]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [35]:
# Unlike a dictionary, though, the Series also supports array-style operations such as slicing

population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

#### Constructing Series objects

We’ve already seen a few ways of constructing a Pandas Series from scratch. where index is an optional argument, and data can be one of many entities.

to wrap up, while constructing pandas series : 
* data can be a list or NumPy array
* data can be a scalar, which is repeated to fill the specified index
* data can be a dictionary, in which index defaults to the sorted dictionary keys
* the index can be explicitly set if a different result is preferred, in this case the Series is populated only with the explicitly identified keys.

In [49]:
# pandas series object with list or numpy array
data = pd.Series(np.array([0.25, 0.5, 0.75, 1.0])) # numpy array
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with scalar value
data = pd.Series(5, index = ('100','200','300'))
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with dictionary
data = pd.Series({2:'a', 1:'b', 3:'c'})
print('constructed by dictionary : \n', data)
print("--"*20)

# pandas series object with explicit index
data = pd.Series({2:'a', 1:'b', 3:'c'}, index = [3,1])
print('constructed by dictionary with explicit index : \n', data)
print("--"*20)

constructed by numpy array :
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
----------------------------------------
constructed by numpy array :
 100    5
200    5
300    5
dtype: int64
----------------------------------------
constructed by dictionary :
 2    a
1    b
3    c
dtype: str
----------------------------------------
constructed by dictionary with explicit index :
 3    c
1    b
dtype: str
----------------------------------------

### The Pandas DataFrame Object

The next fundamental structure in Pandas is the DataFrame. Like the Series object discussed in the previous section, **the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary**

#### DataFrame as a generalized NumPy array

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. 

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, **you can think of a DataFrame as a sequence of aligned Series objects. Here, by “aligned” we mean that they share the same index**

In [53]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)

states = pd.DataFrame({'population' : population,
                        'area' : area})

states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [54]:
'''
Like the Series object, the DataFrame has an index attribute that gives access to the
index labels
'''

print('states index : ', states.index)
print('--'*20)

'''
Additionally, the DataFrame has a columns attribute, which is an Index object holding 
the column labels
'''

print('states columns : ', states.columns)
print('--'*20)

states index :  Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')
----------------------------------------
states columns :  Index(['population', 'area'], dtype='str')
----------------------------------------

#### DataFrame as specialized dictionary

we can also think of a DataFrame as a specialization of a dictionary. Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.

> asking for the 'area' attribute returns the Series object containing the areas

In [64]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional NumPy array, data[0] will return the first row. For a DataFrame, data['col0'] will return the first column. 

Because of this, it is probably better to think about **DataFrames as generalized dictionaries** rather than *generalized arrays*

#### Constructing DataFrame objects

##### From a single Series object. 
A DataFrame is a collection of Series objects, and a single column DataFrame can be constructed from a single Series

In [66]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

##### From a list of dicts 
Any list of dictionaries can be made into a DataFrame. We’ll use a simple list comprehension to create some data

In [ ]:
data = pd.DataFrame({'a' :i,
                    'b' : i+1} for i in range(10,13)
                    )
                    
data

    a   b
0  10  11
1  11  12
2  12  13

In [74]:
'''
Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
“not a number”) values
'''

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

##### From a dictionary of Series objects

As we saw before, a DataFrame can be constructed from a dictionary of Series objects

In [75]:
pd.DataFrame({'population': population,
                'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

##### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each

In [ ]:
pd.DataFrame(np.random.rand(3, 2), # 3 as rows and 2 as cols
            columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

        foo       bar
a  0.976408  0.029823
b  0.009230  0.007841
c  0.691969  0.326241

##### From a NumPy structured array

A Pandas DataFrame operates much like a structured array, and can be created directly from one

In [81]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')]) # numpy structured array
print ('A :', A)
print('--'*20)

pd.DataFrame(A)

A : [(0, 0.) (0, 0.) (0, 0.)]
----------------------------------------

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

* We have seen here that both the Series and DataFrame objects contain an explicit index that lets you reference and modify data.

* This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multiset, as Index objects may contain repeated values)

In [84]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as immutable array

The Index object in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices

In [ ]:
ind[1] # return : 3

ind[::3] # return : Index([2, 7], dtype='int64')

"""
Index objects also have many of the attributes familiar from NumPy arrays
"""

print (ind.shape, ind.size, ind.ndim, ind.dtype)

(5,) 5 1 int64

One difference between **Index objects** and NumPy arrays is that indices are **immutble** that is, they cannot be modified via the normal means

In [112]:
# ind[1] = 99 # return : TypeError: Index does not support mutable operations

#### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic. The Index object follows many of the conventions used by Python’s built-in set data structure, **so that unions, intersections, differences, and other combinations can be computed in a familiar way**

In [111]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

# intersection -> & deprecated
print (indA.intersection(indB))
print('--'*20)

# union -> | deprecated
print (indA.union(indB))
print('--'*20)

# difference -> - deprecated
print (indA.difference(indB))

print('--'*20)
# symmetric_difference -> ^ deprecated
print (indA.symmetric_difference(indB))

Index([3, 5, 7], dtype='int64')
----------------------------------------
Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
----------------------------------------
Index([1, 9], dtype='int64')
----------------------------------------
Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series
As we saw in the previous section, a Series object acts in many ways like a one- dimensional NumPy array, and in many ways like a standard Python dictionary. If we
keep these two overlapping analogies in mind, it will help us to understand the pat‐
terns of data indexing and selection in these arrays

#### Series as dictionary

Like a dictionary, the Series object provides a mapping from a collection of keys to a
collection of values

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['a','b','c','d'])
# index pandas series as dictionary object
print(data['b'])
print('--'*20)

'''
We can also use dictionary-like Python expressions and methods to examine the
keys/indices and values
'''
'a' in data # type: ignore # -> output : True

# accessing the keys and values
data.keys # output : Index(['a', 'b', 'c', 'd'], dtype='str')
data.values # output : array([0.25, 0.5 , 0.75, 1.  ])

# accessing pair of keys and values
list(data.items())

0.5
----------------------------------------

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [130]:
"""
series object is mutable, means :  
Series objects can even be modified with a dictionary-like syntax. Just as you can
extend a dictionary by assigning to a new key, you can extend a Series by assigning
to a new index value
"""

data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series as one-dimensional array

A Series builds on this dictionary-like interface and provides array-style item selection via the **same basic mechanisms as NumPy arrays—that is, slices, masking, and fancy indexing**

In [ ]:
#  slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [136]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [134]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [135]:
# fancy indexing
data[['a','c']]

a    0.25
c    0.75
dtype: float64

Among these, slicing may be the source of the most confusion. Notice that when you
are slicing with an explicit index (i.e., data['a':'c']), the final index is included in
the slice, while when you’re slicing with an implicit index (i.e., data[0:2]), the final
index is excluded from the slice.

#### Indexers: loc, iloc, and ix

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index

Because of this potential confusion in the case of integer indexes, Pandas provides
some special indexer attributes that explicitly expose certain indexing schemes. **These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series**

1. First, the **loc** attribute allows indexing and slicing that always references the **explicit index**

2. The **iloc** attribute allows indexing and slicing that always references the **implicit Python-style index**

3. third indexing attribute, **ix**, is a hybrid of the two, and for Series objects is equivalent to standard []-based indexing. **The purpose of the ix indexer will become more apparent in the context of DataFrame objects**

> One guiding principle of Python code is that “explicit is better than implicit.”

In [150]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

# loc indexer refference explicit index -> return all matches of index
print ('loc indexer')
print(data.loc[1:3]) #return : Series(['a','b], index=[1,3])
print('--'*20)

# iloc indexer refference implicit index -> equal as indexing with [:]
print ('iloc indexer')
print(data.iloc[1:3]) #return : Series(['b','c], index=[3,5]) -> index 0 not include
print('--'*20)

loc indexer
1    a
3    b
dtype: str
----------------------------------------
iloc indexer
3    b
5    c
dtype: str
----------------------------------------

### Data Selection in DataFrame

Recall that a **DataFrame acts in many ways like a two-dimensional or structured array**, and in other ways like a dictionary of Series structures sharing the same index. These analogies can be helpful to keep in mind as we explore data selection within this structure

#### DataFrame as a dictionary

In [33]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                'New York': 141297, 'Florida': 170312,
                'Illinois': 149995})


pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                'New York': 19651127, 'Florida': 19552860,
                'Illinois': 12882135})

data = pd.DataFrame({'area' : area,
                    'pop' : pop})

data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [4]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [7]:
# Equivalently, we can use attribute-style access with column names that are strings
# but not recommended for general use
# because it's not work for all cases. 
# if the column names are not strings, or if the column names conflict
# with methods of the DataFrame, this attribute-style access is not possible.
data.area

# validation
data.area is data['area']

False

In [34]:
# pandas dataframe is mutable
# this dictionary-style syntax can also be used to modify the object, in this case to add a new column

data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### DataFrame as two-dimensional array

As mentioned previously, we can also view the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute

In [ ]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [6]:
'''
With this picture in mind, we can do many familiar array-like observations on the
DataFrame itself. For example, we can transpose the full DataFrame to swap rows and
columns
'''

data.T

      California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

When it comes to indexing of DataFrame objects, however, it is clear that the **dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array**. In particular, **passing a single index to an array accesses a row**

In [ ]:
# try to treat two-dimensional array with simply numpy array indexing method
# in our case, it will return a row

data.values[0] # the values of first row of area, pop dan density column

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [15]:
"""
but, if we passing a single “index” to a DataFrame accesses a column
"""
print(data['area'])

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. 

**Using the iloc indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result**

In [ ]:
# iloc -> implicit index
data.iloc[:3, :2] # first 3 rows and first 2 columns

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [21]:
# loc -> explicit index
data.loc[:'Illinois', :'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Any of the familiar NumPy-style data access patterns can be used within these indexers. For example, in the loc indexer we can combine masking and fancy indexing as in the following

In [28]:
# masking & fancy indexing
data.loc[data['area'] > 150000, ['pop', 'density']]

                   pop     density
California  38332521.0   90.413926
Texas       26448193.0   38.018740
Florida     19552860.0  114.806121

In [35]:
# set or modify value
data.iloc[2,1] = 99
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297        99  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## Operating on Data in Pandas

Pandas includes a couple useful twists, however: **for unary** operations like negation and trigonometric functions, these ufuncs will preserve index and column labels in the output, and **for binary** operations such as addition and multiplication, Pandas will automatically align indices when passing the objects to the ufunc. 

This means that keeping the context of data and combining data from different sources—both potentially error-prone tasks with raw NumPy arrays—become essentially foolproof ones with Pandas. We will additionally see that there are well-defined operations between one-dimensional Series structures and two-dimensional DataFrame structures.


Unary vs Binary 

🔹 Unary = operation with passing through 1 value (sum(), sqrt(), ~, etc.)
🔹 Binary = operation between 2 values or passing 2 values (add (+), sub (-), comp (/))

#### Ufuncs: Index Preservation

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame objects.

In [43]:
'''
If we apply a NumPy ufunc on either of these objects, the result will be another
Pandas object with the indices preserved
'''

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(1,10,4))
ser # pandas series object with index preserved

0    7
1    4
2    8
3    5
dtype: int64

In [42]:
df = pd.DataFrame(data=rng.randint(1,10, (3,4)),
                  columns=['A','B','C','D']
                  )

print(df)

   A  B  C  D
0  3  5  3  7
1  5  9  7  2
2  4  9  2  9

In [45]:
'''
Or, for a slightly more complex calculation
'''
print(np.sin(df * np.pi /4))

              A         B         C         D
0  7.071068e-01 -0.707107  0.707107 -0.707107
1 -7.071068e-01  0.707107 -0.707107  1.000000
2  1.224647e-16  0.707107  1.000000  0.707107

#### UFuncs: Index Alignment

For binary operations on two Series or DataFrame objects, Pandas will align indices in the process of performing the operation. **This is very convenient when you are working with incomplete data, as we’ll see in some of the examples that follow.**

##### Index alignment in Series
As an example, suppose we are combining two different data sources, and find only the top three US states by area and the top three US states by population

In [56]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                    'California': 423967}, name='area')


population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

# Let’s see what happens when we divide these to compute the population density
# densiti area / population

print(area / population)

Alaska             NaN
California    0.011060
New York           NaN
Texas         0.026303
dtype: float64

> The resulting array contains the union of indices of the two input arrays, which we could determine using standard Python set arithmetic on these indices

In [51]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='str')

> Any item for which one or the other does not have an entry is marked with NaN, or “Not a Number,” which is how Pandas marks missing data

This index matching is implemented this way for any of Python’s built-in arithmetic expressions; any missing values are filled in with NaN by default:

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, **we can modify the fill value using appropriate object methods in place of the operators**. For example, calling A.add(B) is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing

In [ ]:
A.add(B, fill_value=0) # forced missing index with fill_value = 0

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### Index alignment in DataFrame

A similar type of alignment takes place for both columns and indices when you are performing operations on DataFrames

In [60]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),
                             columns=list('AB'))

B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                 columns=list('BAC')
                 )

print(A)
print('--'*20)
print(B)
print('--'*20)
print(A+B)

    A  B
0  11  5
1   1  0
----------------------------------------
   B  A  C
0  9  5  8
1  0  9  2
2  6  3  8
----------------------------------------
      A     B   C
0  16.0  14.0 NaN
1  10.0   0.0 NaN
2   NaN   NaN NaN

**Notice that indices are aligned correctly irrespective of their order in the two objects, and indices in the result are sorted**. 

As was the case with Series, **we can use the associated object’s arithmetic method and pass any desired fill_value to be used in place of missing entries**. Here we’ll fill with the mean of all values in A (which we compute by first stacking the rows of A)

In [63]:
print(A.add(B, fill_value=0))

      A     B    C
0  16.0  14.0  8.0
1  10.0   0.0  2.0
2   3.0   6.0  8.0

Mapping between Python operators and Pandas methods

![python-operators-pandas-methods](../images/python-operators-pandas-methods.png)

### Ufuncs: Operations Between DataFrame and Series

When you are performing operations between a DataFrame and a Series, the index and column alignment is similarly maintained. Operations between a DataFrame and a Series are similar to operations between a two-dimensional and one-dimensional NumPy array. Consider one common operation, where we find the difference of a two-dimensional array and one of its rows

In [71]:
A = rng.randint(10, size=(3, 4))
A - A[0]

array([[ 0,  0,  0,  0],
       [-5, -3,  3,  1],
       [-8, -6, -3,  6]])

In [74]:
# subtraction between a two-dimensional array and one of its rows is applied row-wise
df = pd.DataFrame(A, columns=list('QRST'))
print(df)
print('--'*20)
print(df - df.iloc[0])

   Q  R  S  T
0  8  9  4  1
1  3  6  7  2
2  0  3  1  7
----------------------------------------
   Q  R  S  T
0  0  0  0  0
1 -5 -3  3  1
2 -8 -6 -3  6

In [78]:
'''
If you would instead like to operate column-wise, you can use the object methods
mentioned earlier, while specifying the axis keyword
'''
print(df.subtract(df['R'], axis=0))

   Q  R  S  T
0 -1  0 -5 -8
1 -3  0  1 -4
2 -3  0 -2  4

Note that these DataFrame/Series operations, like the operations discussed before, will automatically align indices between the two elements:

In [82]:
halfrow = df.iloc[0, ::2]
print(halfrow)

Q    8
S    4
Name: 0, dtype: int64

In [81]:
print(df - halfrow)

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -5.0 NaN  3.0 NaN
2 -8.0 NaN -3.0 NaN

This preservation and alignment of indices and columns means that operations on data in Pandas will always maintain the data context

> which prevents the types of silly errors that might come up when you are working with heterogeneous and/or misaligned data in raw NumPy arrays

## Handling Missing Data

The difference between data found in many tutorials and data in the real world is that real-world data is rarely clean and homogeneous. In particular, many interesting datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways. we’ll refer to **missing data in general as null, NaN, or NA values**

### Trade-Offs in Missing Data Conventions

A number of schemes have been developed to indicate the presence of missing data in a table or DataFrame. Generally, t**hey revolve around one of two strategies** 

1. **using a mask** that globally indicates missing values

    > In the masking approach, the mask might be an entirely separate Boolean array, or it may involve appropriation of one bit in the data representation to locally indicate the null status of a value.

2. choosing **a sentinel value** that indicates a missing entry

    > In the sentinel approach, the sentinel value could be some data-specific convention, such as indicating a missing integer value with –9999 or some rare bit pattern, or it could be a more global convention, such as indicating a missing floating-point value with NaN (Not a Number), a special value which is part of the IEEE floating-point specification

None of these approaches is without trade-offs: use of a separate mask array requires allocation of an additional Boolean array, which adds overhead in both storage and computation. A sentinel value reduces the range of valid values that can be represented, and may require extra (often non-optimized) logic in CPU and GPU arithmetic. Common special values like NaN are not available for all data types.

**Comparison Table**

| Aspect | Mask | Sentinel Value |
|--------|------|----------------|
| **Definition** | Boolean array showing valid/invalid data | Special value representing missing data |
| **Implementation** | `data[data.notna()]` | `data.fillna(value)` |
| **Destructive** | ❌ Non-destructive | ✅ Destructive |
| **Data Loss** | ❌ No data loss | ✅ Yes (original value lost) |
| **Reversibility** | ✅ Can be reversed | ❌ Cannot be reversed |
| **Memory Usage** | ⚠️ Extra space for boolean array | ✅ More memory efficient |
| **Computation** | ❌ Ignores missing values | ✅ Included in calculation |
| **NaN Handling** | NaN remains | Replaced with concrete value |
| **Database Storage** | ⚠️ NaN may cause issues | ✅ No NaN issues |
| **Aggregation** | ❌ Automatically skips missing | ✅ Included in sum/mean |
| **Statistical Accuracy** | ✅ Accurate (skips invalid) | ❌ Can be skewed (includes sentinel) |
| **Debugging** | ✅ Easy to track missing data | ⚠️ Requires documentation |
| **Performance** | ⚠️ Filtering slower | ✅ Faster computation |
| **Documentation** | ✅ Self-explanatory | ❌ Explicit documentation needed |


**Use Case Comparison**

| Scenario | Mask | Sentinel |
|----------|------|----------|
| **EDA (Exploratory Data Analysis)** | ✅ Recommended | ❌ Not ideal |
| **Data Filtering** | ✅ Recommended | ❌ Not suitable |
| **Database Storage** | ❌ Not ideal | ✅ Recommended |
| **Machine Learning** | ⚠️ Conditional | ✅ Recommended |
| **Legacy System Integration** | ❌ Not suitable | ✅ Recommended |
| **Statistical Analysis** | ✅ Recommended | ❌ Inaccurate |
| **Time Series Data** | ✅ Recommended | ⚠️ Conditional |
| **Financial Data** | ✅ Recommended | ⚠️ Risky |
| **Feature Engineering** | ⚠️ Conditional | ✅ Recommended |
| **Data Quality Check** | ✅ Recommended | ⚠️ Unclear |

**Syntax Comparison**

| Task | Mask | Sentinel Value |
|------|------|----------------|
| **Detect missing** | `data.isna()` | ❌ Not clear |
| **Filter valid** | `data[data.notna()]` | ❌ Risky |
| **Check condition** | `data[condition]` | ❌ May include sentinel |
| **Replace missing** | `data[mask] = value` | `data.fillna(value)` |
| **Count missing** | `data.isna().sum()` | ❌ Not detected |
| **Percentage missing** | `data.isna().sum()/len(data)` | ❌ False 0% |

### Missing Data in Pandas

Pandas chose to use sentinels for missing data, and further chose to use two already-existing **Python null values: the special floating point NaN value**, and the **Python None object**. This choice has some side effects.

#### None: Pythonic missing data

The first sentinel value used by Pandas is **None**, a Python singleton object that is often used for missing data in Python code. 

Because None is **a Python object, it cannot beused in any arbitrary NumPy/Pandas array, but only in arrays with data type 'object' (i.e., arrays of Python objects)**

In [ ]:

vals1 = np.array([1, None, 3, 4])
try :
    results = vals1.sum()
    print('results : ', results)

except :
    print('None type is not supported for sum(). because it is a python object not a numpy number')

None type is not supported for sum(). because it is a python object not a numpy number

Conclusion: None vs np.nan

| Aspect | Explanation |
|--------|-------------|
| ❌ **Why doesn't None work?** | NumPy array has a fixed dtype (data type remains constant). `None` is a Python object, not a numeric type, so it cannot be used in arithmetic operations. |
| ✅ **What's the solution?** | Use `np.nan` (float type) as the representation for missing values, not `None` (object type). `np.nan` is numeric and can be used in NumPy operations. |
| 🐍 **When to use None?** | Use `None` in pure Python code, not in NumPy arrays. Example: `if x is None:` in Python conditional statements. |
| 📊 **When to use np.nan?** | Use `np.nan` in NumPy arrays, Pandas DataFrames, or Pandas Series for proper representation of missing values. |

#### NaN: Missing numerical data

The other missing data representation, **NaN (acronym for Not a Number)**, is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation

In [97]:
vals2 = np.array([1,np.nan,3,4])
vals2.dtype # return : float
vals2

array([ 1., nan,  3.,  4.])

* **Notice that NumPy chose a native floating-point type for this array**

* this means that unlike the object array from before, **this array supports fast operations pushed into compiled code**

* You should be aware that NaN is a bit like a data virus—it infects any other object it touches. 

* **Regardless of the operation, the result of arithmetic with NaN will be another NaN**

In [104]:
# np.nan support fast operation like : addition dans multiplication
print(2 + vals2) 
print(2 * vals2) 
print("--"*20)

# notice the result of arithmetic with NaN will be another NaN:
print(1 + np.nan) # return nan
print(2*np.nan) # return nan
print("--"*20)

# means when we aggregate these values, we get NaN
print("aggeregating nan values : ")
print(vals2.sum())
print(vals2.mean())
print(vals2.std())

[ 3. nan  5.  6.]
[ 2. nan  6.  8.]
----------------------------------------
nan
nan
----------------------------------------
aggeregating nan values :
nan
nan
nan

In [106]:
'''
NumPy does provide some special aggregations 
that will ignore these missing values
'''
print('nan_sum : ', np.nansum(vals2))
print('nan_mean : ', np.nanmean(vals2))
print('nan_std : ', np.nanstd(vals2))
print('nan_max : ', np.nanmax(vals2))
print('nan_min : ', np.nanmin(vals2))

nan_sum :  8.0
nan_mean :  2.6666666666666665
nan_std :  1.247219128924647
nan_max :  4.0
nan_min :  1.0

#### NaN and None in Pandas

NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate

In [108]:
x = pd.Series(range(2))
print(x)
print("--"*20)

x[0] = None
print(x)
print("--"*20)

0    0
1    1
dtype: int64
----------------------------------------
0    NaN
1    1.0
dtype: float64
----------------------------------------

* Notice that in addition to casting the integer array to floating point,**Pandas automatically converts the None to a NaN value. (Be aware that there is a proposal to add a native integer NA to Pandas in the future**

* as of this writing, it has not been included.)

* While this type of magic may feel a bit hackish compared to the more unified
approach to NA values in domain-specific languages like R, **the Pandas sentinel/casting approach works quite well in practice and in my experience only rarely causes issues**

![pandas-handling-na](../images/pandas-handling-na.png)

> Keep in mind that in Pandas, string data is always stored with an object dtype.

##### Quick Reference Guide: Handling Missing Data

| Context | Use | Check | Handle |
|:---:|:---:|:---:|:---:|
| 🐍 **Python** | `None` | `x is None` | `if x is None:` |
| 🗄️ **Database** | `NULL` | `IS NULL` | `COALESCE()` |
| 📊 **NumPy** | `np.nan` | `np.isnan(x)` | `np.nansum()` |
| 🐼 **Pandas** | `np.nan` / `None` | `df.isna()` | `df.fillna()` |
| 📡 **JSON** | `null` | Parse check | Varies |
| 🎯 **General** | Missing values | Contextual | Strategic |


##### Detailed Comparison Tables: None vs NULL vs Missing Values vs NaN

###### Table 1: Basic Characteristics

| Aspect | None | NULL | Missing Values | NaN |
|:-------|:-----|:-----|:---------------:|:---:|
| **Context** | Python | Database (SQL) | General concept | NumPy/Pandas |
| **Type System** | `NoneType` | N/A | Abstract | `float` |
| **Numeric Type** | ❌ No | N/A | N/A | ✅ Yes |
| **Arithmetic Operations** | ❌ ERROR | N/A | Context-dependent | ✅ Propagates |
| **Equality Check** | `is None` | `IS NULL` | Method-dependent | `np.isnan()` |
| **Array Behavior** | Forces object dtype | N/A | Library-specific | Works with float |
| **Memory** | Constant (singleton) | N/A | Varies | 8 bytes (float64) |

######  Table 2: Detecting Missing Data

| Detection Method | None | NULL | NaN | Best Practice |
|:---|:---|:---|:---|:---|
| **Pure Python** | `x is None` | N/A | `math.isnan(x)` | Use `is None` for None |
| **NumPy Array** | ❌ Won't work properly | N/A | `np.isnan(x)` | Always use for arrays |
| **Pandas DataFrame** | `df.isna()` | Auto-converts | `df.isna()` | Recommended |
| **Pandas Series** | `s.isnull()` | Auto-converts | `s.isnull()` | Alias for isna() |
| **Count Missing** | `sum(x is None)` | `COUNT(*)` | `np.isnan(x).sum()` | Library-specific |

######  Table 3: Handling Missing Data

| Operation | None | NULL | NaN | Example |
|:---|:---|:---|:---|:---|
| **Count missing** | `x is None` count | `COUNT(*)` | `np.isnan().sum()` | Library-specific |
| **Filter data** | `[x for x in arr if x is not None]` | `WHERE ... IS NOT NULL` | `arr[~np.isnan(arr)]` | Different syntax |
| **Replace missing** | `x if x is not None else val` | `COALESCE(col, val)` | `np.nan_to_num()` | Different methods |
| **Aggregate data** | ❌ Skip manually | ❌ Skip automatically | `np.nanmean()` | Use nan-aware |
| **Fill missing** | Manual loop | `UPDATE` statement | `df.fillna()` | Library-specific |

######  Table 4: Library-Specific Representation

| Library | Supports None | Supports NULL | Represents Missing | Supports NaN |
|:---|:---:|:---:|:---:|:---:|
| **Python** | ✅ Native | ❌ No | ❌ No | Via float only |
| **NumPy** | ❌ Forces object | ❌ No | ❌ No | ✅ Native |
| **Pandas** | ✅ Auto-convert to NaN | ✅ Auto-convert | ✅ Yes | ✅ Native |
| **SQL** | Via NULL | ✅ Native | Via NULL | ❌ No |
| **JSON** | No (becomes null) | Via null | Via null | No |

######  Table 5: Quick Reference by Use Case

| Scenario | Use This | Check With | Handle With | Example |
|:---|:---|:---|:---|:---|
| **Pure Python function** | `None` | `is None` | `if x is None:` | API parameters |
| **Database query** | `NULL` | `IS NULL` | `WHERE`, `COALESCE` | SQL queries |
| **NumPy array** | `np.nan` | `np.isnan(x)` | `np.nansum()`, filter | Scientific data |
| **Pandas Series** | `np.nan` or `None` | `df.isna()` | `df.fillna()` | Data frames |
| **JSON API** | `null` | Convert to None | Python-dependent | Web APIs |
| **Dictionary** | `None` | `x is None` | `get()`, `if` | Config files |
| **Data Analysis** | Missing tracking | Context method | Strategy-based | EDA phase |

#### Operating on Null Values

As we have seen, Pandas treats None and NaN as essentially interchangeable for indicating missing or null values. To facilitate this convention

*there are several useful methods for detecting, removing, and replacing null values in Pandas data structures*. They are:

1. isnull() : Generate a Boolean mask indicating missing values

2. notnull() : Opposite of isnull()

3. dropna() : Return a filtered version of the data

4. fillna() : Return a copy of the data with missing values filled or imputed

##### Detecting null values

Pandas data structures have two useful methods for detecting null data: isnull() and notnull(). Either one will return a Boolean mask over the data

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])

# is.null()
print(data.isnull())

# boolean mask can be directly used to filter data

'''
The isnull() and notnull() methods produce similar Boolean results for Data
Frames.
'''
data[data.notnull()]

0    False
1     True
2    False
3     True
dtype: bool

0        1
2    hello
dtype: object

##### Dropping null values

In addition to the masking used before, there are the convenience methods, dropna() (which removes NA values) and fillna() (which fills in NA values).

In [125]:
# For a Series, the result is straightforward
data.dropna()

0        1
2    hello
dtype: object

In [126]:
# For a DataFrame, there are more options. Consider the following DataFrame
df = pd.DataFrame([[1, np.nan, 2],
                    [2, 3, 5],
                    [np.nan, 4, 6]])

df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [136]:
'''
We cannot drop single values from a DataFrame; we can only drop full rows or full
columns. Depending on the application, you might want one or the other, so
dropna() gives a number of options for a DataFrame.
'''

# drop all rows in which any null value is present
print('drop all rows in which any null value is present : ') 
df.dropna()

drop all rows in which any null value is present :

     0    1  2
1  2.0  3.0  5

In [138]:
# drop all Columns in which any null value is present

print('drop all columns in which any null value is present : ') 
df.dropna(axis=1) # axis = 1 means columns
df.dropna(axis='columns')

drop all columns in which any null value is present :

   2
0  2
1  5
2  6

notice that : 

> The default is how='any', such that any row or column (depending on the axis key‐word) containing a null value will be dropped. You can also specify how='all', which will only drop rows/columns that are all null values

In [143]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [145]:
# drop rows in which all values are missing
print('drop rows where all values are missing : ')
df.dropna(how='all')

drop rows where all values are missing :

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [140]:
# drop columns in which all values are missing
print('drop columns where all values are missing : ')
df.dropna(axis='columns', how='all')

drop columns where all values are missing :

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

> For finer-grained control, the thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept

In [ ]:
# we only drop rows in which a certain number of rows are missing. in this case, 3 missing values on rows
df.dropna(thresh=3)

     0    1  2   3
1  2.0  3.0  5 NaN

##### Filling null values

Sometimes rather than dropping NA values, *you’d rather replace them with a valid value*. 

This value might be a single number like zero, or it might be some sort of imputation or interpolation from the good values. You could do this in-place using the isnull() method as a mask, but because it is such a common operation Pandas provides the **fillna()** method, which returns a copy of the array with the null values replaced.

In [150]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [151]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
# We can specify a forward-fill to propagate the previous value forward:
data.ffill()

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
#  we can specify a back-fill to propagate the next values backward:
data.bfill()

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [164]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [165]:
'''
For DataFrames, the options are similar, but we can also specify an axis along which
the fills take place

notice that if a previous value is not available during a forward fill, the NA value
remains.
'''

df.ffill(axis='columns')

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## Hierarchical Indexing