In [2]:
# all library and packages used in this notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

# Data Manipulation with Pandas

Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame. **DataFrames are essentially multidimensional arrays with attached row and column labels**, and often with heterogeneous types and/or missing data. 

As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

As we saw, NumPy’s ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks. **its limitations become clear when :**

1. when we need more flexibility (attaching labels to data, working with missing data, etc.)
2. when attempting operations that do not map well to element-wise broadcasting (groupings, pivots,etc.)

## Introducing Pandas Objects

### The Pandas Series Object

A Pandas Series is a **one-dimensional array** of indexed data. **It can be created from a list or array**

In [14]:
# pandas series object
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data.index
data.index.values # show values of pandas object

array([0, 1, 2, 3])

In [ ]:
"""
Like with a NumPy array, data can be accessed by the associated index via the familiar
Python square-bracket notation
"""
data[0] # output : np.float64(0.25)
data[:2]

0    0.25
1    0.50
dtype: float64

#### Series as generalized NumPy array

From what we’ve seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. 

The essential difference is the presence of the index: 

 - while the NumPy array has an implicitly defined integer index used
to access the values
- the Pandas Series has an explicitly defined index associated with the values

    - This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. **if we wish, we can use strings as an index**

In [29]:
# create pandas object with non integer as index

data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index = ('a','b','c','d'))

data.index.values # output : <StringArray>['a', 'b', 'c', 'd'] Length: 4, dtype: str
print(data)
print("--"*20)
# And the item access works as expected
data['b']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
----------------------------------------

np.float64(0.5)

#### Series as specialized dictionary

In this way, you can think of a Pandas Series a bit like a specialization of a Python dictionary. **A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values**

In [33]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [35]:
# Unlike a dictionary, though, the Series also supports array-style operations such as slicing

population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

#### Constructing Series objects

We’ve already seen a few ways of constructing a Pandas Series from scratch. where index is an optional argument, and data can be one of many entities.

to wrap up, while constructing pandas series : 
* data can be a list or NumPy array
* data can be a scalar, which is repeated to fill the specified index
* data can be a dictionary, in which index defaults to the sorted dictionary keys
* the index can be explicitly set if a different result is preferred, in this case the Series is populated only with the explicitly identified keys.

In [49]:
# pandas series object with list or numpy array
data = pd.Series(np.array([0.25, 0.5, 0.75, 1.0])) # numpy array
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with scalar value
data = pd.Series(5, index = ('100','200','300'))
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with dictionary
data = pd.Series({2:'a', 1:'b', 3:'c'})
print('constructed by dictionary : \n', data)
print("--"*20)

# pandas series object with explicit index
data = pd.Series({2:'a', 1:'b', 3:'c'}, index = [3,1])
print('constructed by dictionary with explicit index : \n', data)
print("--"*20)

constructed by numpy array :
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
----------------------------------------
constructed by numpy array :
 100    5
200    5
300    5
dtype: int64
----------------------------------------
constructed by dictionary :
 2    a
1    b
3    c
dtype: str
----------------------------------------
constructed by dictionary with explicit index :
 3    c
1    b
dtype: str
----------------------------------------

### The Pandas DataFrame Object

The next fundamental structure in Pandas is the DataFrame. Like the Series object discussed in the previous section, **the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary**

#### DataFrame as a generalized NumPy array

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. 

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, **you can think of a DataFrame as a sequence of aligned Series objects. Here, by “aligned” we mean that they share the same index**

In [53]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)

states = pd.DataFrame({'population' : population,
                        'area' : area})

states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [54]:
'''
Like the Series object, the DataFrame has an index attribute that gives access to the
index labels
'''

print('states index : ', states.index)
print('--'*20)

'''
Additionally, the DataFrame has a columns attribute, which is an Index object holding 
the column labels
'''

print('states columns : ', states.columns)
print('--'*20)

states index :  Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')
----------------------------------------
states columns :  Index(['population', 'area'], dtype='str')
----------------------------------------

#### DataFrame as specialized dictionary

we can also think of a DataFrame as a specialization of a dictionary. Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.

> asking for the 'area' attribute returns the Series object containing the areas

In [64]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional NumPy array, data[0] will return the first row. For a DataFrame, data['col0'] will return the first column. 

Because of this, it is probably better to think about **DataFrames as generalized dictionaries** rather than *generalized arrays*

#### Constructing DataFrame objects

##### From a single Series object. 
A DataFrame is a collection of Series objects, and a single column DataFrame can be constructed from a single Series

In [66]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

##### From a list of dicts 
Any list of dictionaries can be made into a DataFrame. We’ll use a simple list comprehension to create some data

In [ ]:
data = pd.DataFrame({'a' :i,
                    'b' : i+1} for i in range(10,13)
                    )
                    
data

    a   b
0  10  11
1  11  12
2  12  13

In [74]:
'''
Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
“not a number”) values
'''

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

##### From a dictionary of Series objects

As we saw before, a DataFrame can be constructed from a dictionary of Series objects

In [75]:
pd.DataFrame({'population': population,
                'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

##### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each

In [ ]:
pd.DataFrame(np.random.rand(3, 2), # 3 as rows and 2 as cols
            columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

        foo       bar
a  0.976408  0.029823
b  0.009230  0.007841
c  0.691969  0.326241

##### From a NumPy structured array

A Pandas DataFrame operates much like a structured array, and can be created directly from one

In [81]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')]) # numpy structured array
print ('A :', A)
print('--'*20)

pd.DataFrame(A)

A : [(0, 0.) (0, 0.) (0, 0.)]
----------------------------------------

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

* We have seen here that both the Series and DataFrame objects contain an explicit index that lets you reference and modify data.

* This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multiset, as Index objects may contain repeated values)

In [84]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

#### Index as immutable array

The Index object in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices

In [ ]:
ind[1] # return : 3

ind[::3] # return : Index([2, 7], dtype='int64')

"""
Index objects also have many of the attributes familiar from NumPy arrays
"""

print (ind.shape, ind.size, ind.ndim, ind.dtype)

(5,) 5 1 int64

One difference between **Index objects** and NumPy arrays is that indices are **immutble** that is, they cannot be modified via the normal means

In [112]:
# ind[1] = 99 # return : TypeError: Index does not support mutable operations

#### Index as ordered set

Pandas objects are designed to facilitate operations such as joins across datasets, which depend on many aspects of set arithmetic. The Index object follows many of the conventions used by Python’s built-in set data structure, **so that unions, intersections, differences, and other combinations can be computed in a familiar way**

In [111]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

# intersection -> & deprecated
print (indA.intersection(indB))
print('--'*20)

# union -> | deprecated
print (indA.union(indB))
print('--'*20)

# difference -> - deprecated
print (indA.difference(indB))

print('--'*20)
# symmetric_difference -> ^ deprecated
print (indA.symmetric_difference(indB))

Index([3, 5, 7], dtype='int64')
----------------------------------------
Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
----------------------------------------
Index([1, 9], dtype='int64')
----------------------------------------
Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series
As we saw in the previous section, a Series object acts in many ways like a one- dimensional NumPy array, and in many ways like a standard Python dictionary. If we
keep these two overlapping analogies in mind, it will help us to understand the pat‐
terns of data indexing and selection in these arrays

#### Series as dictionary

Like a dictionary, the Series object provides a mapping from a collection of keys to a
collection of values

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['a','b','c','d'])
# index pandas series as dictionary object
print(data['b'])
print('--'*20)

'''
We can also use dictionary-like Python expressions and methods to examine the
keys/indices and values
'''
'a' in data # type: ignore # -> output : True

# accessing the keys and values
data.keys # output : Index(['a', 'b', 'c', 'd'], dtype='str')
data.values # output : array([0.25, 0.5 , 0.75, 1.  ])

# accessing pair of keys and values
list(data.items())

0.5
----------------------------------------

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [130]:
"""
series object is mutable, means :  
Series objects can even be modified with a dictionary-like syntax. Just as you can
extend a dictionary by assigning to a new key, you can extend a Series by assigning
to a new index value
"""

data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series as one-dimensional array

A Series builds on this dictionary-like interface and provides array-style item selection via the **same basic mechanisms as NumPy arrays—that is, slices, masking, and fancy indexing**

In [ ]:
#  slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [136]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [134]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [135]:
# fancy indexing
data[['a','c']]

a    0.25
c    0.75
dtype: float64

Among these, slicing may be the source of the most confusion. Notice that when you
are slicing with an explicit index (i.e., data['a':'c']), the final index is included in
the slice, while when you’re slicing with an implicit index (i.e., data[0:2]), the final
index is excluded from the slice.

#### Indexers: loc, iloc, and ix

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index

Because of this potential confusion in the case of integer indexes, Pandas provides
some special indexer attributes that explicitly expose certain indexing schemes. **These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series**

1. First, the **loc** attribute allows indexing and slicing that always references the **explicit index**

2. The **iloc** attribute allows indexing and slicing that always references the **implicit Python-style index**

3. third indexing attribute, **ix**, is a hybrid of the two, and for Series objects is equivalent to standard []-based indexing. **The purpose of the ix indexer will become more apparent in the context of DataFrame objects**

> One guiding principle of Python code is that “explicit is better than implicit.”

In [150]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

# loc indexer refference explicit index -> return all matches of index
print ('loc indexer')
print(data.loc[1:3]) #return : Series(['a','b], index=[1,3])
print('--'*20)

# iloc indexer refference implicit index -> equal as indexing with [:]
print ('iloc indexer')
print(data.iloc[1:3]) #return : Series(['b','c], index=[3,5]) -> index 0 not include
print('--'*20)

loc indexer
1    a
3    b
dtype: str
----------------------------------------
iloc indexer
3    b
5    c
dtype: str
----------------------------------------

### Data Selection in DataFrame

Recall that a **DataFrame acts in many ways like a two-dimensional or structured array**, and in other ways like a dictionary of Series structures sharing the same index. These analogies can be helpful to keep in mind as we explore data selection within this structure

#### DataFrame as a dictionary

In [33]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                'New York': 141297, 'Florida': 170312,
                'Illinois': 149995})


pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                'New York': 19651127, 'Florida': 19552860,
                'Illinois': 12882135})

data = pd.DataFrame({'area' : area,
                    'pop' : pop})

data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [4]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [7]:
# Equivalently, we can use attribute-style access with column names that are strings
# but not recommended for general use
# because it's not work for all cases. 
# if the column names are not strings, or if the column names conflict
# with methods of the DataFrame, this attribute-style access is not possible.
data.area

# validation
data.area is data['area']

False

In [34]:
# pandas dataframe is mutable
# this dictionary-style syntax can also be used to modify the object, in this case to add a new column

data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### DataFrame as two-dimensional array

As mentioned previously, we can also view the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute

In [ ]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [6]:
'''
With this picture in mind, we can do many familiar array-like observations on the
DataFrame itself. For example, we can transpose the full DataFrame to swap rows and
columns
'''

data.T

      California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

When it comes to indexing of DataFrame objects, however, it is clear that the **dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array**. In particular, **passing a single index to an array accesses a row**

In [ ]:
# try to treat two-dimensional array with simply numpy array indexing method
# in our case, it will return a row

data.values[0] # the values of first row of area, pop dan density column

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [15]:
"""
but, if we passing a single “index” to a DataFrame accesses a column
"""
print(data['area'])

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. 

**Using the iloc indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result**

In [ ]:
# iloc -> implicit index
data.iloc[:3, :2] # first 3 rows and first 2 columns

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [21]:
# loc -> explicit index
data.loc[:'Illinois', :'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Any of the familiar NumPy-style data access patterns can be used within these indexers. For example, in the loc indexer we can combine masking and fancy indexing as in the following

In [28]:
# masking & fancy indexing
data.loc[data['area'] > 150000, ['pop', 'density']]

                   pop     density
California  38332521.0   90.413926
Texas       26448193.0   38.018740
Florida     19552860.0  114.806121

In [35]:
# set or modify value
data.iloc[2,1] = 99
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297        99  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

## Operating on Data in Pandas

Pandas includes a couple useful twists, however: **for unary** operations like negation and trigonometric functions, these ufuncs will preserve index and column labels in the output, and **for binary** operations such as addition and multiplication, Pandas will automatically align indices when passing the objects to the ufunc. 

This means that keeping the context of data and combining data from different sources—both potentially error-prone tasks with raw NumPy arrays—become essentially foolproof ones with Pandas. We will additionally see that there are well-defined operations between one-dimensional Series structures and two-dimensional DataFrame structures.


Unary vs Binary 

🔹 Unary = operation with passing through 1 value (sum(), sqrt(), ~, etc.)
🔹 Binary = operation between 2 values or passing 2 values (add (+), sub (-), comp (/))

#### Ufuncs: Index Preservation

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas Series and DataFrame objects.

In [43]:
'''
If we apply a NumPy ufunc on either of these objects, the result will be another
Pandas object with the indices preserved
'''

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(1,10,4))
ser # pandas series object with index preserved

0    7
1    4
2    8
3    5
dtype: int64

In [42]:
df = pd.DataFrame(data=rng.randint(1,10, (3,4)),
                  columns=['A','B','C','D']
                  )

print(df)

   A  B  C  D
0  3  5  3  7
1  5  9  7  2
2  4  9  2  9

In [45]:
'''
Or, for a slightly more complex calculation
'''
print(np.sin(df * np.pi /4))

              A         B         C         D
0  7.071068e-01 -0.707107  0.707107 -0.707107
1 -7.071068e-01  0.707107 -0.707107  1.000000
2  1.224647e-16  0.707107  1.000000  0.707107

#### UFuncs: Index Alignment

For binary operations on two Series or DataFrame objects, Pandas will align indices in the process of performing the operation. **This is very convenient when you are working with incomplete data, as we’ll see in some of the examples that follow.**

##### Index alignment in Series
As an example, suppose we are combining two different data sources, and find only the top three US states by area and the top three US states by population

In [56]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                    'California': 423967}, name='area')


population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

# Let’s see what happens when we divide these to compute the population density
# densiti area / population

print(area / population)

Alaska             NaN
California    0.011060
New York           NaN
Texas         0.026303
dtype: float64

> The resulting array contains the union of indices of the two input arrays, which we could determine using standard Python set arithmetic on these indices

In [51]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='str')

> Any item for which one or the other does not have an entry is marked with NaN, or “Not a Number,” which is how Pandas marks missing data

This index matching is implemented this way for any of Python’s built-in arithmetic expressions; any missing values are filled in with NaN by default:

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, **we can modify the fill value using appropriate object methods in place of the operators**. For example, calling A.add(B) is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing

In [ ]:
A.add(B, fill_value=0) # forced missing index with fill_value = 0

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

##### Index alignment in DataFrame

A similar type of alignment takes place for both columns and indices when you are performing operations on DataFrames

In [60]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),
                             columns=list('AB'))

B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                 columns=list('BAC')
                 )

print(A)
print('--'*20)
print(B)
print('--'*20)
print(A+B)

    A  B
0  11  5
1   1  0
----------------------------------------
   B  A  C
0  9  5  8
1  0  9  2
2  6  3  8
----------------------------------------
      A     B   C
0  16.0  14.0 NaN
1  10.0   0.0 NaN
2   NaN   NaN NaN

**Notice that indices are aligned correctly irrespective of their order in the two objects, and indices in the result are sorted**. 

As was the case with Series, **we can use the associated object’s arithmetic method and pass any desired fill_value to be used in place of missing entries**. Here we’ll fill with the mean of all values in A (which we compute by first stacking the rows of A)

In [63]:
print(A.add(B, fill_value=0))

      A     B    C
0  16.0  14.0  8.0
1  10.0   0.0  2.0
2   3.0   6.0  8.0

Mapping between Python operators and Pandas methods

![python-operators-pandas-methods](../images/python-operators-pandas-methods.png)

### Ufuncs: Operations Between DataFrame and Series

When you are performing operations between a DataFrame and a Series, the index and column alignment is similarly maintained. Operations between a DataFrame and a Series are similar to operations between a two-dimensional and one-dimensional NumPy array. Consider one common operation, where we find the difference of a two-dimensional array and one of its rows

In [71]:
A = rng.randint(10, size=(3, 4))
A - A[0]

array([[ 0,  0,  0,  0],
       [-5, -3,  3,  1],
       [-8, -6, -3,  6]])

In [74]:
# subtraction between a two-dimensional array and one of its rows is applied row-wise
df = pd.DataFrame(A, columns=list('QRST'))
print(df)
print('--'*20)
print(df - df.iloc[0])

   Q  R  S  T
0  8  9  4  1
1  3  6  7  2
2  0  3  1  7
----------------------------------------
   Q  R  S  T
0  0  0  0  0
1 -5 -3  3  1
2 -8 -6 -3  6

In [78]:
'''
If you would instead like to operate column-wise, you can use the object methods
mentioned earlier, while specifying the axis keyword
'''
print(df.subtract(df['R'], axis=0))

   Q  R  S  T
0 -1  0 -5 -8
1 -3  0  1 -4
2 -3  0 -2  4

Note that these DataFrame/Series operations, like the operations discussed before, will automatically align indices between the two elements:

In [82]:
halfrow = df.iloc[0, ::2]
print(halfrow)

Q    8
S    4
Name: 0, dtype: int64

In [81]:
print(df - halfrow)

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -5.0 NaN  3.0 NaN
2 -8.0 NaN -3.0 NaN

This preservation and alignment of indices and columns means that operations on data in Pandas will always maintain the data context

> which prevents the types of silly errors that might come up when you are working with heterogeneous and/or misaligned data in raw NumPy arrays

## Handling Missing Data

The difference between data found in many tutorials and data in the real world is that real-world data is rarely clean and homogeneous. In particular, many interesting datasets will have some amount of data missing. To make matters even more complicated, different data sources may indicate missing data in different ways. we’ll refer to **missing data in general as null, NaN, or NA values**

### Trade-Offs in Missing Data Conventions

A number of schemes have been developed to indicate the presence of missing data in a table or DataFrame. Generally, t**hey revolve around one of two strategies** 

1. **using a mask** that globally indicates missing values

    > In the masking approach, the mask might be an entirely separate Boolean array, or it may involve appropriation of one bit in the data representation to locally indicate the null status of a value.

2. choosing **a sentinel value** that indicates a missing entry

    > In the sentinel approach, the sentinel value could be some data-specific convention, such as indicating a missing integer value with –9999 or some rare bit pattern, or it could be a more global convention, such as indicating a missing floating-point value with NaN (Not a Number), a special value which is part of the IEEE floating-point specification

None of these approaches is without trade-offs: use of a separate mask array requires allocation of an additional Boolean array, which adds overhead in both storage and computation. A sentinel value reduces the range of valid values that can be represented, and may require extra (often non-optimized) logic in CPU and GPU arithmetic. Common special values like NaN are not available for all data types.

**Comparison Table**

| Aspect | Mask | Sentinel Value |
|--------|------|----------------|
| **Definition** | Boolean array showing valid/invalid data | Special value representing missing data |
| **Implementation** | `data[data.notna()]` | `data.fillna(value)` |
| **Destructive** | ❌ Non-destructive | ✅ Destructive |
| **Data Loss** | ❌ No data loss | ✅ Yes (original value lost) |
| **Reversibility** | ✅ Can be reversed | ❌ Cannot be reversed |
| **Memory Usage** | ⚠️ Extra space for boolean array | ✅ More memory efficient |
| **Computation** | ❌ Ignores missing values | ✅ Included in calculation |
| **NaN Handling** | NaN remains | Replaced with concrete value |
| **Database Storage** | ⚠️ NaN may cause issues | ✅ No NaN issues |
| **Aggregation** | ❌ Automatically skips missing | ✅ Included in sum/mean |
| **Statistical Accuracy** | ✅ Accurate (skips invalid) | ❌ Can be skewed (includes sentinel) |
| **Debugging** | ✅ Easy to track missing data | ⚠️ Requires documentation |
| **Performance** | ⚠️ Filtering slower | ✅ Faster computation |
| **Documentation** | ✅ Self-explanatory | ❌ Explicit documentation needed |


**Use Case Comparison**

| Scenario | Mask | Sentinel |
|----------|------|----------|
| **EDA (Exploratory Data Analysis)** | ✅ Recommended | ❌ Not ideal |
| **Data Filtering** | ✅ Recommended | ❌ Not suitable |
| **Database Storage** | ❌ Not ideal | ✅ Recommended |
| **Machine Learning** | ⚠️ Conditional | ✅ Recommended |
| **Legacy System Integration** | ❌ Not suitable | ✅ Recommended |
| **Statistical Analysis** | ✅ Recommended | ❌ Inaccurate |
| **Time Series Data** | ✅ Recommended | ⚠️ Conditional |
| **Financial Data** | ✅ Recommended | ⚠️ Risky |
| **Feature Engineering** | ⚠️ Conditional | ✅ Recommended |
| **Data Quality Check** | ✅ Recommended | ⚠️ Unclear |

**Syntax Comparison**

| Task | Mask | Sentinel Value |
|------|------|----------------|
| **Detect missing** | `data.isna()` | ❌ Not clear |
| **Filter valid** | `data[data.notna()]` | ❌ Risky |
| **Check condition** | `data[condition]` | ❌ May include sentinel |
| **Replace missing** | `data[mask] = value` | `data.fillna(value)` |
| **Count missing** | `data.isna().sum()` | ❌ Not detected |
| **Percentage missing** | `data.isna().sum()/len(data)` | ❌ False 0% |

### Missing Data in Pandas

Pandas chose to use sentinels for missing data, and further chose to use two already-existing **Python null values: the special floating point NaN value**, and the **Python None object**. This choice has some side effects.

#### None: Pythonic missing data

The first sentinel value used by Pandas is **None**, a Python singleton object that is often used for missing data in Python code. 

Because None is **a Python object, it cannot beused in any arbitrary NumPy/Pandas array, but only in arrays with data type 'object' (i.e., arrays of Python objects)**

In [ ]:

vals1 = np.array([1, None, 3, 4])
try :
    results = vals1.sum()
    print('results : ', results)

except :
    print('None type is not supported for sum(). because it is a python object not a numpy number')

None type is not supported for sum(). because it is a python object not a numpy number

Conclusion: None vs np.nan

| Aspect | Explanation |
|--------|-------------|
| ❌ **Why doesn't None work?** | NumPy array has a fixed dtype (data type remains constant). `None` is a Python object, not a numeric type, so it cannot be used in arithmetic operations. |
| ✅ **What's the solution?** | Use `np.nan` (float type) as the representation for missing values, not `None` (object type). `np.nan` is numeric and can be used in NumPy operations. |
| 🐍 **When to use None?** | Use `None` in pure Python code, not in NumPy arrays. Example: `if x is None:` in Python conditional statements. |
| 📊 **When to use np.nan?** | Use `np.nan` in NumPy arrays, Pandas DataFrames, or Pandas Series for proper representation of missing values. |

#### NaN: Missing numerical data

The other missing data representation, **NaN (acronym for Not a Number)**, is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation

In [97]:
vals2 = np.array([1,np.nan,3,4])
vals2.dtype # return : float
vals2

array([ 1., nan,  3.,  4.])

* **Notice that NumPy chose a native floating-point type for this array**

* this means that unlike the object array from before, **this array supports fast operations pushed into compiled code**

* You should be aware that NaN is a bit like a data virus—it infects any other object it touches. 

* **Regardless of the operation, the result of arithmetic with NaN will be another NaN**

In [104]:
# np.nan support fast operation like : addition dans multiplication
print(2 + vals2) 
print(2 * vals2) 
print("--"*20)

# notice the result of arithmetic with NaN will be another NaN:
print(1 + np.nan) # return nan
print(2*np.nan) # return nan
print("--"*20)

# means when we aggregate these values, we get NaN
print("aggeregating nan values : ")
print(vals2.sum())
print(vals2.mean())
print(vals2.std())

[ 3. nan  5.  6.]
[ 2. nan  6.  8.]
----------------------------------------
nan
nan
----------------------------------------
aggeregating nan values :
nan
nan
nan

In [106]:
'''
NumPy does provide some special aggregations 
that will ignore these missing values
'''
print('nan_sum : ', np.nansum(vals2))
print('nan_mean : ', np.nanmean(vals2))
print('nan_std : ', np.nanstd(vals2))
print('nan_max : ', np.nanmax(vals2))
print('nan_min : ', np.nanmin(vals2))

nan_sum :  8.0
nan_mean :  2.6666666666666665
nan_std :  1.247219128924647
nan_max :  4.0
nan_min :  1.0

#### NaN and None in Pandas

NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate

In [108]:
x = pd.Series(range(2))
print(x)
print("--"*20)

x[0] = None
print(x)
print("--"*20)

0    0
1    1
dtype: int64
----------------------------------------
0    NaN
1    1.0
dtype: float64
----------------------------------------

* Notice that in addition to casting the integer array to floating point,**Pandas automatically converts the None to a NaN value. (Be aware that there is a proposal to add a native integer NA to Pandas in the future**

* as of this writing, it has not been included.)

* While this type of magic may feel a bit hackish compared to the more unified
approach to NA values in domain-specific languages like R, **the Pandas sentinel/casting approach works quite well in practice and in my experience only rarely causes issues**

![pandas-handling-na](../images/pandas-handling-na.png)

> Keep in mind that in Pandas, string data is always stored with an object dtype.

##### Quick Reference Guide: Handling Missing Data

| Context | Use | Check | Handle |
|:---:|:---:|:---:|:---:|
| 🐍 **Python** | `None` | `x is None` | `if x is None:` |
| 🗄️ **Database** | `NULL` | `IS NULL` | `COALESCE()` |
| 📊 **NumPy** | `np.nan` | `np.isnan(x)` | `np.nansum()` |
| 🐼 **Pandas** | `np.nan` / `None` | `df.isna()` | `df.fillna()` |
| 📡 **JSON** | `null` | Parse check | Varies |
| 🎯 **General** | Missing values | Contextual | Strategic |


##### Detailed Comparison Tables: None vs NULL vs Missing Values vs NaN

###### Table 1: Basic Characteristics

| Aspect | None | NULL | Missing Values | NaN |
|:-------|:-----|:-----|:---------------:|:---:|
| **Context** | Python | Database (SQL) | General concept | NumPy/Pandas |
| **Type System** | `NoneType` | N/A | Abstract | `float` |
| **Numeric Type** | ❌ No | N/A | N/A | ✅ Yes |
| **Arithmetic Operations** | ❌ ERROR | N/A | Context-dependent | ✅ Propagates |
| **Equality Check** | `is None` | `IS NULL` | Method-dependent | `np.isnan()` |
| **Array Behavior** | Forces object dtype | N/A | Library-specific | Works with float |
| **Memory** | Constant (singleton) | N/A | Varies | 8 bytes (float64) |

######  Table 2: Detecting Missing Data

| Detection Method | None | NULL | NaN | Best Practice |
|:---|:---|:---|:---|:---|
| **Pure Python** | `x is None` | N/A | `math.isnan(x)` | Use `is None` for None |
| **NumPy Array** | ❌ Won't work properly | N/A | `np.isnan(x)` | Always use for arrays |
| **Pandas DataFrame** | `df.isna()` | Auto-converts | `df.isna()` | Recommended |
| **Pandas Series** | `s.isnull()` | Auto-converts | `s.isnull()` | Alias for isna() |
| **Count Missing** | `sum(x is None)` | `COUNT(*)` | `np.isnan(x).sum()` | Library-specific |

######  Table 3: Handling Missing Data

| Operation | None | NULL | NaN | Example |
|:---|:---|:---|:---|:---|
| **Count missing** | `x is None` count | `COUNT(*)` | `np.isnan().sum()` | Library-specific |
| **Filter data** | `[x for x in arr if x is not None]` | `WHERE ... IS NOT NULL` | `arr[~np.isnan(arr)]` | Different syntax |
| **Replace missing** | `x if x is not None else val` | `COALESCE(col, val)` | `np.nan_to_num()` | Different methods |
| **Aggregate data** | ❌ Skip manually | ❌ Skip automatically | `np.nanmean()` | Use nan-aware |
| **Fill missing** | Manual loop | `UPDATE` statement | `df.fillna()` | Library-specific |

######  Table 4: Library-Specific Representation

| Library | Supports None | Supports NULL | Represents Missing | Supports NaN |
|:---|:---:|:---:|:---:|:---:|
| **Python** | ✅ Native | ❌ No | ❌ No | Via float only |
| **NumPy** | ❌ Forces object | ❌ No | ❌ No | ✅ Native |
| **Pandas** | ✅ Auto-convert to NaN | ✅ Auto-convert | ✅ Yes | ✅ Native |
| **SQL** | Via NULL | ✅ Native | Via NULL | ❌ No |
| **JSON** | No (becomes null) | Via null | Via null | No |

######  Table 5: Quick Reference by Use Case

| Scenario | Use This | Check With | Handle With | Example |
|:---|:---|:---|:---|:---|
| **Pure Python function** | `None` | `is None` | `if x is None:` | API parameters |
| **Database query** | `NULL` | `IS NULL` | `WHERE`, `COALESCE` | SQL queries |
| **NumPy array** | `np.nan` | `np.isnan(x)` | `np.nansum()`, filter | Scientific data |
| **Pandas Series** | `np.nan` or `None` | `df.isna()` | `df.fillna()` | Data frames |
| **JSON API** | `null` | Convert to None | Python-dependent | Web APIs |
| **Dictionary** | `None` | `x is None` | `get()`, `if` | Config files |
| **Data Analysis** | Missing tracking | Context method | Strategy-based | EDA phase |

#### Operating on Null Values

As we have seen, Pandas treats None and NaN as essentially interchangeable for indicating missing or null values. To facilitate this convention

*there are several useful methods for detecting, removing, and replacing null values in Pandas data structures*. They are:

1. isnull() : Generate a Boolean mask indicating missing values

2. notnull() : Opposite of isnull()

3. dropna() : Return a filtered version of the data

4. fillna() : Return a copy of the data with missing values filled or imputed

##### Detecting null values

Pandas data structures have two useful methods for detecting null data: isnull() and notnull(). Either one will return a Boolean mask over the data

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])

# is.null()
print(data.isnull())

# boolean mask can be directly used to filter data

'''
The isnull() and notnull() methods produce similar Boolean results for Data
Frames.
'''
data[data.notnull()]

0    False
1     True
2    False
3     True
dtype: bool

0        1
2    hello
dtype: object

##### Dropping null values

In addition to the masking used before, there are the convenience methods, dropna() (which removes NA values) and fillna() (which fills in NA values).

In [125]:
# For a Series, the result is straightforward
data.dropna()

0        1
2    hello
dtype: object

In [126]:
# For a DataFrame, there are more options. Consider the following DataFrame
df = pd.DataFrame([[1, np.nan, 2],
                    [2, 3, 5],
                    [np.nan, 4, 6]])

df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [136]:
'''
We cannot drop single values from a DataFrame; we can only drop full rows or full
columns. Depending on the application, you might want one or the other, so
dropna() gives a number of options for a DataFrame.
'''

# drop all rows in which any null value is present
print('drop all rows in which any null value is present : ') 
df.dropna()

drop all rows in which any null value is present :

     0    1  2
1  2.0  3.0  5

In [138]:
# drop all Columns in which any null value is present

print('drop all columns in which any null value is present : ') 
df.dropna(axis=1) # axis = 1 means columns
df.dropna(axis='columns')

drop all columns in which any null value is present :

   2
0  2
1  5
2  6

notice that : 

> The default is how='any', such that any row or column (depending on the axis key‐word) containing a null value will be dropped. You can also specify how='all', which will only drop rows/columns that are all null values

In [143]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [145]:
# drop rows in which all values are missing
print('drop rows where all values are missing : ')
df.dropna(how='all')

drop rows where all values are missing :

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [140]:
# drop columns in which all values are missing
print('drop columns where all values are missing : ')
df.dropna(axis='columns', how='all')

drop columns where all values are missing :

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

> For finer-grained control, the thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept

In [ ]:
# we only drop rows in which a certain number of rows are missing. in this case, 3 missing values on rows
df.dropna(thresh=3)

     0    1  2   3
1  2.0  3.0  5 NaN

##### Filling null values

Sometimes rather than dropping NA values, *you’d rather replace them with a valid value*. 

This value might be a single number like zero, or it might be some sort of imputation or interpolation from the good values. You could do this in-place using the isnull() method as a mask, but because it is such a common operation Pandas provides the **fillna()** method, which returns a copy of the array with the null values replaced.

In [150]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [151]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
# We can specify a forward-fill to propagate the previous value forward:
data.ffill()

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
#  we can specify a back-fill to propagate the next values backward:
data.bfill()

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [164]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [165]:
'''
For DataFrames, the options are similar, but we can also specify an axis along which
the fills take place

notice that if a previous value is not available during a forward fill, the NA value
remains.
'''

df.ffill(axis='columns')

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## Hierarchical Indexing

Often it is useful to go beyond this and store higher-dimensional data—that is, **data indexed by more than one or two keys.** While Pandas does provide Panel and Panel4D objects that natively handle three-dimensional and four-dimensional data a far more common pattern in practice is to make use of **hierarchical indexing (also known as multi-indexing) to incorporate multiple index levels within a single index. In this way, higher-dimensional data can be compactly represented within the familiar one-dimensional Series and two-dimensional DataFrame objects**

In this section, we’ll explore the direct creation of MultiIndex objects; 

> considerations around indexing, slicing, and computing statistics across multiply indexed data; and useful routines for converting between simple and hierarchically indexed representations of your data.

### A Multiply Indexed Series

In [35]:
index = [('California', 2000), ('California', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956,
                18976457, 19378102,
                20851820, 25145561]

pop = pd.Series(populations, index=index)
print(pop)
print('--'*20)

''' 
With this indexing scheme, you can straightforwardly index or slice the series based
on this multiple index
'''

print(pop[('California', 2000):('Texas', 2000)])


'''
all convenience indexing is offer, when we need to access a particular row or column.
for example, we only want return 2010 population for all states
'''
print('\n-- return 2010 population for all states --')

for i in pop.index:
    if i[1] == 2010 :
        print(i, pop[i])

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64
----------------------------------------
(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

-- return 2010 population for all states --
('California', 2010) 37253956
('New York', 2010) 19378102
('Texas', 2010) 25145561

#### The better way: Pandas MultiIndex

Fortunately, Pandas provides a better way. Our tuple-based indexing is essentially a rudimentary multi-index, and the **Pandas MultiIndex** type gives us the type of operations we wish to have. We can create a multi-index from the tuples as follows

In [36]:
# pandas multiindex
index = pd.MultiIndex.from_tuples(pop.index)
print(index)
print('--'*20)
print('-- reindex --')
# reindexing - multiple index in good way
pop = pop.reindex(index)
print(pop)

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )
----------------------------------------
-- reindex --
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

Here the **first two columns of the Series representation show the multiple index values, while the third column shows the data**. Notice that some entries are missing in the first column: in this multi-index representation, any blank entry indicates the same value as the line above it.

Now to access all data for which the second index is 2010, we can simply use the Pandas slicing notation

In [37]:
# simply alternative way - recommended
print('--'*20)
print(pop.xs(2010,level=1))

----------------------------------------
California    37253956
New York      19378102
Texas         25145561
dtype: int64

#### MultiIndex as extra dimension

You might notice something else here: we could easily have stored the same data
using a simple DataFrame with index and column labels. In fact, Pandas is built with this equivalence in mind. 

**The unstack() method will quickly convert a multiply indexed Series into a conventionally indexed DataFrame**

In [259]:
# convert multiindex to dataframe -> rows and columns
pop_df = pop.unstack()
print(pop_df)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [260]:
# Naturally, the stack() method provides the opposite operation
print(pop_df.stack())

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

Seeing this, you might wonder why would we would bother with hierarchical indexing at all. 
> The reason is simple: just as we were able to use multi-indexing to represent two-dimensional data within a one-dimensional Series, we can also use it to represent data of three or more dimensions in a Series or DataFrame. 

Each extra level in a multi-index represents an extra dimension of data; taking advantage of this property gives us much more flexibility in the types of data we can represent. 

Concretely, we might want to add another column of demographic data for each state at each year (say, population under 18); with a MultiIndex this is as easy as adding another column to the DataFrame

In [261]:
# adding new column into multi-index dataframe

pop_df = pd.DataFrame({'total' : pop,
                       'under18': [9267089, 9284094,
                                    4687374, 4318033,
                                    5906301, 6879014]
                                    })

print(pop_df)

                    total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [262]:
'''
all the ufuncs and other functionality. work with hierarchical indices as well.
Here we compute the fraction of people under 18 by year, given the above data
'''

f_u18 = pop_df['under18'] / pop_df['total']
print(f_u18.unstack())

                2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

### Methods of MultiIndex Creation

The most straightforward way to construct a multiply indexed Series or DataFrame is to simply pass a list of two or more index arrays to the constructor.

In [263]:
df = pd.DataFrame(np.random.rand(4, 2),
                    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                    columns=['data1', 'data2'])
print(df)

        data1     data2
a 1  0.861046  0.340386
  2  0.206978  0.185917
b 1  0.451088  0.352661
  2  0.241777  0.726972

In [265]:
'''
Similarly, if you pass a dictionary with appropriate tuples as keys, 
Pandas will automatically recognize this and use a MultiIndex by default
'''

data = {('California', 2000): 33871648,
('California', 2010): 37253956,
('Texas', 2000): 20851820,
('Texas', 2010): 25145561,
('New York', 2000): 18976457,
('New York', 2010): 19378102}

print(pd.Series(data))

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

#### Explicit MultiIndex constructors

For more flexibility in how the index is constructed, you can instead use the class method constructors available in the **pd.MultiIndex.**

In [34]:
# create multiindex explicitly from arrays
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

# create multiindex explicitly from tuples
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

# create multiindex from cartesian product of arrays
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

# create multiindex from encoding by passing levels
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
            codes=[[0, 0, 1, 1], [0, 1, 0, 1]]) # codes == lables

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

#### MultiIndex level names

Sometimes it is convenient to name the levels of the MultiIndex. You can accomplish this by passing the names argument to any of the above MultiIndex constructors, or by setting the names attribute of the index after the fact

In [40]:
pop.index.names = ['state', 'year']
print(pop)

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### MultiIndex for columns

In a DataFrame, the rows and columns are completely symmetric, and just as the rows can have multiple levels of indices, **the columns can have multiple levels as well**

In [16]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
print(health_data)

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      51.0  37.0  43.0  36.3  41.0  37.5
     2      50.0  38.1  49.0  35.8  38.0  39.2
2014 1      32.0  38.6  22.0  35.6  51.0  38.2
     2      40.0  36.3  37.0  38.1  46.0  36.0

In [291]:
print(health_data['Guido'])

type          HR  Temp
year visit
2013 1      42.0  36.1
     2      38.0  36.1
2014 1      38.0  37.8
     2      35.0  38.5

### Indexing and Slicing a MultiIndex

Indexing and slicing on a MultiIndex is designed to be intuitive, and it helps if you think about the indices as added dimensions. We’ll first look at indexing multiply indexed Series, and then multiply indexed DataFrames

#### Multiply indexed Series

We can access single elements by indexing with multiple terms

In [293]:
# mutilpleindex series = pop , same as we create before
pop[('California',2010)]

np.int64(37253956)

In [298]:
'''
The MultiIndex also supports partial indexing, or indexing just one of the levels in
the index. The result is another Series, with the lower-level indices maintained
'''
print(pop['California'])

year
2000    33871648
2010    37253956
dtype: int64

In [300]:
# Partial slicing is available as well, as long as the MultiIndex is sorted
print(pop.loc['California' : 'Texas'])

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [ ]:
"""
With sorted indices, we can perform partial indexing on lower levels by 
passing an empty slice in the first index 
""" 
print(pop.loc[:,2010])

state
California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [303]:
# Other types of indexing and selection
print(pop[pop > 22000000])

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [304]:
# Selection based on fancy indexing also works
print(pop[['California', 'Texas']])

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Multiply indexed DataFrames

A multiply indexed DataFrame behaves in a similar manner. Consider our toy medical DataFrame from before

In [ ]:
print(health_data)

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      46.0  36.5  42.0  36.1  63.0  37.7
     2      32.0  36.9  38.0  36.1  46.0  36.5
2014 1      41.0  38.9  38.0  37.8  31.0  35.8
     2      19.0  39.4  35.0  38.5  31.0  37.1

**Remember that columns are primary in a DataFrame**, and the syntax used for multiply indexed Series applies to the columns. For example, we can recover Guido’s heart rate data with a simple operation

In [332]:
print(health_data['Guido','HR'])

year  visit
2013  1        42.0
      2        38.0
2014  1        38.0
      2        35.0
Name: (Guido, HR), dtype: float64

Also, as with the single-index case, **we can use the loc, iloc, and ix indexers**

In [334]:
# loc indexers
print(health_data.loc[:, ('Bob', 'HR')])

year  visit
2013  1        46.0
      2        32.0
2014  1        41.0
      2        19.0
Name: (Bob, HR), dtype: float64

Working with slices within these index tuples is not especially convenient; 
trying to create a slice within a tuple will lead to a syntax error:

In [17]:
try:
    health_data.loc[:, 'HR']
except KeyError as e:
    print(type(e))
    print(e)

<class 'KeyError'>
'HR'

> You could get around this by building the desired slice explicitly using Python’s built in **slice()** function, but a better way in this context is to use an IndexSlice object, which Pandas provides for precisely this situation. For example

> or you should consider using xs indexer

In [ ]:
idx = pd.IndexSlice
print(health_data.loc[idx[2014, 1], idx[:, 'HR']])

subject  type
Bob      HR      46.0
Guido    HR      42.0
Sue      HR      63.0
Name: (2013, 1), dtype: float64

### Rearranging Multi-Indices

One of the keys to working with multiply indexed data is knowing how to effectively transform the data. There are a number of operations that will preserve all the information in the dataset, but rearrange it for the purposes of various computations. 

We saw a brief example of this in the stack() and unstack() methods, but there are many more ways to finely control the rearrangement of data between hierarchical indices and columns

#### Sorted and unsorted indices

Many of the MultiIndex slicing operations will fail if the index is not sorted. We’ll start by creating some simple multiply indexed data where the indices are not
lexographically sorted

In [22]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']

data

char  int
a     1      0.614493
      2      0.705926
c     1      0.849886
      2      0.891366
b     1      0.455155
      2      0.487375
dtype: float64

In [ ]:
# If we try to take a partial slice of this index, it will result in an error

try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'

Although it is not entirely clear from the error message, this is the result of the MultiIndex not being sorted. 

For various reasons, partial slices and other similar operations require the levels in the MultiIndex to be in sorted (i.e., lexographical) order. Pandas provides a number of convenience routines to perform this type of sorting; 

examples are the **sort_index() and sortlevel()** methods of the DataFrame. We’ll use the simplest, sort_index()

In [28]:
# sort index
data = data.sort_index()
data

char  int
a     1      0.614493
      2      0.705926
b     1      0.455155
      2      0.487375
c     1      0.849886
      2      0.891366
dtype: float64

In [29]:
# With the index sorted in this way, partial slicing will work as expected
print(data['a':'b'])

char  int
a     1      0.614493
      2      0.705926
b     1      0.455155
      2      0.487375
dtype: float64

#### Stacking and unstacking indices

In [45]:
# unstacking
print(pop.unstack(level=0)) # level = 0 -> state

print('--'*20)

print(pop.unstack(level=1)) # level = 1 -> year

state  California  New York     Texas
year
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561
----------------------------------------
year            2000      2010
state
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [47]:
# The opposite of unstack() is stack(), which here can be used to recover the original series
print(pop.unstack().stack())

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Index setting and resetting

Another way to rearrange hierarchical data is to turn the index labels into columns; this can be accomplished with the reset_index method. 

Calling this on the population dictionary will result in a DataFrame with a state and year column holding the information that was formerly in the index. For clarity, we can optionally specify the name of the data for the column representation

In [48]:
# index resetting

pop_flat = pop.reset_index(name='population')
print(pop_flat)

        state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

Often when you are working with data in the real world, the raw input data looks like this and it’s useful to build a MultiIndex from the column values. This can be done with the set_index method of the DataFrame, which returns a multiply indexed Data Frame

In [49]:
# building multiindex from column values
print(pop_flat.set_index(['state','year']))

                 population
state      year
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

### Data Aggregations on Multi-Indices

**We’ve previously seen that Pandas has built-in data aggregation methods, such as mean(), sum(), and max()**. 

For hierarchically indexed data, t**hese can be passed a level parameter** that controls which subset of the data the aggregate is computed on

> keep in mind for clarity, all aggregated operation should be computed with groupby() method

In [51]:
# let's back with our health_data

print(health_data)

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      51.0  37.0  43.0  36.3  41.0  37.5
     2      50.0  38.1  49.0  35.8  38.0  39.2
2014 1      32.0  38.6  22.0  35.6  51.0  38.2
     2      40.0  36.3  37.0  38.1  46.0  36.0

In [87]:
# try compute mean by year
data_mean = health_data.groupby(level='year').mean() # level = 1-> by visit all year
print(data_mean)

subject   Bob        Guido          Sue
type       HR   Temp    HR   Temp    HR   Temp
year
2013     50.5  37.55  46.0  36.05  39.5  38.35
2014     36.0  37.45  29.5  36.85  48.5  37.10

In [89]:
"""
By further making use of the axis keyword, we can take the mean among levels on
the columns as well
"""

print(data_mean.T.groupby(level='type').mean().T) # should be included Transpose, because group by currenly only work on axis = 0 or row

type         HR       Temp
year
2013  45.333333  37.316667
2014  38.000000  37.133333

## Combining Datasets: Concat and Append

Some of the most interesting studies of data come from combining different data sources. These operations can involve anything from very straightforward concatenation of two different datasets, to more complicated database-style joins and merges that correctly handle any overlaps between the datasets. Series and DataFrames are built with this type of operation in mind, and Pandas includes functions and methods that make this sort of data wrangling fast and straightforward


#### Simple Concatenation with pd.concat

Pandas has a function, pd.concat(), which has a similar syntax to np.concatenate but contains a number of options that we’ll discuss momentarily

pd.concat() can be used for a simple concatenation of Series or DataFrame objects, just as np.concatenate() can be used for simple concatenations of arrays

In [115]:
# pd.concat
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

print(pd.concat([ser1, ser2]))

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

In [17]:
# It also works to concatenate higher-dimensional objects, such as DataFrames
import pandas as pd
import numpy as np

def make_df(cols, ind):
    data = np.random.randint(10, 100, size=(len(ind), len(cols)))
    return pd.DataFrame(data, columns=list(cols), index=ind)

df1 = make_df('ABC', range(3))
df2 = make_df('ABC', range(3))

print(pd.concat([df1,df2]))

# by default, pd.concat will use the axis = 0, but we can specify axis = 1 to concatenate along the columns

    A   B   C
0  69  15  32
1  90  71  33
2  16  40  53
0  79  56  33
1  40  93  84
2  52  11  53

#### Duplicate indices

One important difference between np.concatenate and pd.concat is that Pandas concatenation preserves indices, **even if the result will have duplicate indices!**

In [ ]:
"""
Notice the repeated indices in the result. While this is valid within DataFrames, 
the outcome is often undesirable. pd.concat() gives us a few ways to handle it.
"""

print(df1);print(df2);print(pd.concat([df1,df2])) # pd.concat(axis=default=0)

    A   B   C
0  89  98  99
1  55  31  67
2  74  82  37
    A   B   C
0  18  43  75
1  97  95  95
2  44  92  94
    A   B   C
0  89  98  99
1  55  31  67
2  74  82  37
0  18  43  75
1  97  95  95
2  44  92  94

#### Catching the repeats as an error

If you’d like to simply verify that the indices in the result of pd.concat() do not overlap, you can specify the **verify_integrity** flag.

With this set to True, the concatenation will raise an exception if there are duplicate indices. Here is an example, where for clarity we’ll catch and print the error message:

In [127]:
X = pd.DataFrame(np.random.rand(3, 2), columns=['A', 'B'])
Y = pd.DataFrame(np.random.rand(3, 2), columns=['A', 'B'])

try:
    pd.concat([X,Y], verify_integrity=True)
except ValueError as e:
    print('value error : ', e)

value error :  Indexes have overlapping values: Index([0, 1, 2], dtype='int64')

#### Ignoring the index

Sometimes the index itself does not matter, and you would prefer it to simply be ignored. You can specify this option using the ignore_index flag. With this set to True, the concatenation will create a new integer index for the resulting Series

In [130]:
# try to igonoring the index
print(pd.concat([X,Y], ignore_index=True))

          A         B
0  0.834596  0.485503
1  0.053742  0.662480
2  0.737197  0.129481
3  0.653664  0.944944
4  0.819459  0.279798
5  0.157689  0.783862

#### Adding MultiIndex keys

Another alternative is to use the keys option to specify a label for the data sources; the result will be a hierarchically indexed series containing the data

In [131]:
# adding multi-index keys
print(pd.concat([X, Y], keys=['x', 'y']))

            A         B
x 0  0.834596  0.485503
  1  0.053742  0.662480
  2  0.737197  0.129481
y 0  0.653664  0.944944
  1  0.819459  0.279798
  2  0.157689  0.783862

#### Concatenation with joins

In the simple examples we just looked at, we were mainly concatenating DataFrames with shared column names. In practice, data from different sources might have different sets of column names, and pd.concat offers several options in this case. Consider the concatenation of the following two DataFrames, which have some (but not all!) columns in common

In [11]:
df5 = make_df('ABC', [0, 1])
df6 = make_df('BCD', [2, 3])

print(df5), print(df6), print(pd.concat([df5, df6]))

    A   B   C
0  93  94  17
1  11  54  41
    B   C   D
2  74  76  85
3  56  14  91
      A   B   C     D
0  93.0  94  17   NaN
1  11.0  54  41   NaN
2   NaN  74  76  85.0
3   NaN  56  14  91.0

(None, None, None)

By default, the entries for which no data is available are filled with NA values. To change this, we can specify one of several options for the join and join_axes parameters of the concatenate function. By default, the join is a union of the input columns (join='outer'), but we can change this to an intersection of the columns using
join='inner'

In [12]:
print(df5); print(df6);
print(pd.concat([df5, df6], join='inner'))

    A   B   C
0  93  94  17
1  11  54  41
    B   C   D
2  74  76  85
3  56  14  91
    B   C
0  94  17
1  54  41
2  74  76
3  56  14

Another option is to directly specify the index of the remaining colums using the join_axes argument, which takes a list of index objects. Here we’ll specify that the returned columns should be the same as those of the first input

> keep in mind, join_axes will act like left join, this keyword also depreceated on pandas 2.0+

## Combining Datasets: Merge and Join

One essential feature offered by Pandas is its high-performance, in-memory join and merge operations. If you have ever worked with databases, you should be familiar with this type of data interaction. The main interface for this is the **pd.merge function**, and we’ll see a few examples of how this can work in practice

### Relational Algebra

The behavior implemented in pd.merge() is a subset of what is known as relational algebra, which is a formal set of rules for manipulating relational data, and forms the conceptual foundation of operations available in most databases

The strength of relational algebra approach is that **it proposes several primitive operations**, which become the building blocks of more complicated operations on any dataset. With this lexicon of fundamental operations implemented efficiently in a database or other program, a wide range of fairly complicated composite operations can be performed

Pandas implements several of these fundamental building blocks in the **pd.merge()function and the related join() method of Series and DataFrames**. As we will see, these let you efficiently link data from different sources

### Categories of Joins

The pd.merge() function implements a number of types of joins: **the one-to-one, many-to-one, and many-to-many joins**. All three types of joins are accessed via an identical call to the pd.merge() interface; the type of join performed depends on the form of the input data.

#### One-to-one joins

> Perhaps the simplest type of merge expression is the one-to-one join, which is in many ways very similar to the column-wise concatenation

In [22]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

print(df1)
print(df2)
print('--'*10, 'one-to-one merge','--'*10)

print(df1.merge(df2))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
-------------------- one-to-one merge --------------------
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

The pd.merge() function recognizes that each DataFrame has an “employee” column, and automatically joins using this column as a key.

The result of the merge is a new DataFrame that combines the information from the two inputs. Notice that the order of entries in each column is not necessarily maintained: in this case, the order of the “employee” column differs between df1 and df2, and the pd.merge() function correctly accounts for this. 

Additionally, keep in mind that the merge in general discards the index, except in the special case of merges by index

#### Many-to-one joins

**Many-to-one joins are joins in which one of the two key columns contains duplicate entries**. For the many-to-one case, the resulting DataFrame will preserve those duplicate entries as appropriate

In [28]:
df3 =pd.merge(df1, df2)

df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

print (df4)
print('--'*20, 'many-to-one merge','--'*20)
print(pd.merge(df3,df4))

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
---------------------------------------- many-to-one merge ----------------------------------------
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

The resulting DataFrame has an additional column with the “supervisor” information, where the information is repeated in one or more locations as required by the inputs

#### Many-to-many joins

Many-to-many joins are a bit confusing conceptually, but are nevertheless well defined. **If the key column in both the left and right array contains duplicates, then the result is a many-to-many merge**. 

This will be perhaps most clear with a concrete example. Consider the following, where we have a DataFrame showing one or more skills associated with a particular group

In [34]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                    'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']})

print(df5);print(df1);
print('--'*20, 'many-to-many merge','--'*20)
print(pd.merge(df1, df5))

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
---------------------------------------- many-to-many merge ----------------------------------------
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

These three types of joins can be used with other Pandas tools to implement a wide array of functionality. But in practice, datasets are rarely as clean as the one we’re working with here. In the following section, we’ll consider some of the options provided by pd.merge() that enable you to tune how the join operations work.

### Specification of the Merge Key

We’ve already seen the default behavior of pd.merge(): it looks for one or more matching column names between the two inputs, and uses this as the key. However, often the column names will not match so nicely, and pd.merge() provides a variety of options for handling this.

#### The on keyword

Most simply, you can explicitly specify the name of the key column using the on keyword, which takes a column name or a list of column names

> This option works only if both the left and right DataFrames have the specified column name

In [36]:
print(df1);print(df2)
print('--'*20, 'merging on keyword','--'*20)
print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
---------------------------------------- merging on keyword ----------------------------------------
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

#### The left_on and right_on keywords (based on column's name)

At times you may wish to merge two datasets with different column names; for example,we may have a dataset in which the employee name is labeled as “name” rather than “employee”. In this case, we can use the left_on and right_on keywords to specify the two column names

In [37]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})

print(df1);print(df3)
print('--'*20, 'merging on keyword with different column name','--'*20)
print(pd.merge(df1, df3, left_on='employee', right_on='name'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
---------------------------------------- merging on keyword with different column name ----------------------------------------
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [ ]:
'''
The result has a redundant column that we can drop if desired—for example, by
using the drop() method of DataFrames
'''
print(pd.merge(df1, df3, left_on='employee', right_on='name').drop('name', axis=1))

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

#### The left_index and right_index keywords

Sometimes, rather than merging on a column, you would instead like to merge on an index. For example, your data might look like this

In [45]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a); print(df2a)
print('--'*20, 'merging on index','--'*20)

print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
---------------------------------------- merging on index ----------------------------------------
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [46]:
'''
For convenience, DataFrames implement the join() method, which performs a
merge that defaults to joining on indices:
'''
print(df1a.join(df2a, how='inner'))

                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

If you’d like to mix indices and columns, you can combine left_index with right_on or left_on with right_index to get the desired behavior

In [49]:
# combine left_index with right_on (column name)
print('--'*20, 'combine left_index with right_on (column name)','--'*20)
print(pd.merge(df1a, df3, left_index=True, right_on='name'))

---------------------------------------- combine left_index with right_on (column name) ----------------------------------------
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

#### Specifying Set Arithmetic for Joins

In all the preceding examples we have glossed over one important consideration in performing a join: **the type of set arithmetic used in the join**. 

This comes up when a value appears in one key column but not the other.

In [54]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                    columns=['name', 'food'])

df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                    columns=['name', 'drink'])

print(df6);print(df7);
print('--'*20, 'merge with how=inner as default','--'*20)
print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
---------------------------------------- merge with how=inner as default ----------------------------------------
   name   food drink
0  Mary  bread  wine

Here we have merged two datasets that have only a single “name” entry in common: Mary. 

By default, **the result contains the intersection of the two sets of inputs**; this is what is known as an inner join. We can specify this explicitly using the how keyword, which defaults to 'inner'

Other options for the how keyword are **'outer', 'left', and 'right'**. An outer join returns a join over the union of the input columns, and fills in all missing values with NAs

In [55]:
print(df6); print(df7); 
print('--'*20, 'merge with how=outer','--'*20)
print(pd.merge(df6, df7, how='outer'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
---------------------------------------- merge with how=outer ----------------------------------------
     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [56]:
print(df6); print(df7); 
print('--'*20, 'merge with how=right','--'*20)
print(pd.merge(df6, df7, how='right'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
---------------------------------------- merge with how=right ----------------------------------------
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

#### Overlapping Column Names: The suffixes Keyword

Finally, you may end up in a case where your two input DataFrames have **conflicting column names**

In [62]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})

df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})

print(df8);print(df9)
print('--'*20, 'merge while col names are conflicting','--'*20)
print(pd.merge(df8, df9, on='name')) #notice, by default pd.merge will add the suffixes _x and _y to disambiguate the overlapping 'rank' column

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2
---------------------------------------- merge while col names are conflicting ----------------------------------------
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

Because the output would have two conflicting column names, the merge function automatically appends a suffix _x or _y to make the output columns unique. 

If these defaults are inappropriate, **it is possible to specify a custom suffix using the suffixes keyword**

In [ ]:
# adding specific suffixes to disambiguate the overlapping 'rank' column
# These suffixes work in any of the possible join patterns, and work also if there are multiple overlapping columns.
print(pd.merge(df8, df9, on='name', suffixes=['_left', '_right']))

   name  rank_left  rank_right
0   Bob          1           3
1  Jake          2           1
2  Lisa          3           4
3   Sue          4           2

## Aggregation and Grouping

An essential piece of analysis of large data is efficient summarization.

computing aggregations like **sum(), mean(), median(), min(), and max()**, in which a single number gives insight into the nature of a potentially large dataset

from simple operations akin to what we’ve seen on NumPy arrays, **to more sophisticated operations based on the concept of a groupby**.

### Planets Data

Here we will use the Planets dataset from sns module.It gives information on planets that astronomers have discovered around other stars (known as extrasolar planets or exoplanets for
short)

In [67]:
import seaborn as sns

planets = sns.load_dataset('planets')
print('shape :',planets.shape)
print(planets.head())

shape : (1035, 6)
            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

### Simple Aggregation in Pandas

Earlier we explored some of the data aggregations available for NumPy arrays. 
As with a one-dimensional NumPy array, for a Pandas Series the aggregates return a single value

In [74]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
print(ser)
print('--' *20)
print('sum :',ser.sum())
print('mean :',ser.mean())

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64
----------------------------------------
sum : 2.811925491708157
mean : 0.5623850983416314

In [81]:
''' 
For a DataFrame, by default the aggregates return results within each column
'''

df = pd.DataFrame({'A': rng.rand(5),
                    'B': rng.rand(5)})
print(df)
print('--'*20)
print('sum :\n', df.sum()) # notice by default, the sum is computed for each column
print('mean :\n', df.mean()) # notice by default, the mean is computed for each column

          A         B
0  0.662522  0.969585
1  0.311711  0.775133
2  0.520068  0.939499
3  0.546710  0.894827
4  0.184854  0.597900
----------------------------------------
sum :
 A    2.225866
B    4.176944
dtype: float64
mean :
 A    0.445173
B    0.835389
dtype: float64

In [ ]:
''' 
By specifying the axis argument, you can instead aggregate within each row
'''
print('sum by row :\n', df.sum(axis='columns')) # notice axis = 'columns' means sum by row
print('mean by row :\n', df.mean(axis='columns')) # notice axis =

sum by row :
 0    1.632107
1    1.086844
2    1.459567
3    1.441538
4    0.782754
dtype: float64
mean by row :
 0    0.816053
1    0.543422
2    0.729783
3    0.720769
4    0.391377
dtype: float64

Pandas Series and DataFrames include all of the common aggregates. in addition, there is a convenience method describe() that computes several common aggregates for each column and returns the result. Let’s use this on the Planets data, for now dropping rows with missing values

In [85]:
print(planets.describe())

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

This can be a useful way to begin understanding the overall properties of a dataset. For example, we see in the year column that although exoplanets were discovered as far back as 1989, half of all known exoplanets were not discovered until 2010 or after.

This is largely thanks to the Kepler mission, which is a space-based telescope specifically designed for finding eclipsing planets around other stars

![pandas-aggregation](../images/pandas-aggregation.png)

These are all methods of DataFrame and Series objects

### GroupBy: Split, Apply, Combine

Simple aggregations can give you a flavor of your dataset, but often we would prefer to **aggregate conditionally on some label or index**: this is implemented in the so called **groupby** operation. 

The name “group by” comes from a command in the SQL database language, but it is perhaps more illuminative to think of it in the terms first coined by Hadley Wickham of Rstats fame: split, apply, combine

#### Split, apply, combine

- The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.

- The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.

- The combine step merges the results of these operations into an output array.

![split-apply-combine](../images/split-apply-combine.png)

In [4]:
# groupby method
import pandas as pd
df = pd.DataFrame(data=
                  {'key':['A', 'B', 'C','A','B','C'],
                  'data' : range(6)},
                  columns=['key','data'])

print(df.groupby('key').sum()) # return : <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f8c9c1e5d90>

     data
key
A       3
B       5
C       7

#### The GroupBy object

The GroupBy object is a very flexible abstraction. In many ways, you can simply treat
it as if it’s a collection of DataFrames, and it does the difficult things under the hood.

Perhaps the most important operations made available by a GroupBy are aggregate, filter, transform, and apply. but before that let’s introduce some of the other functionality that can be used with the basic GroupBy operation.

GroupBy Techniques : 

1. Column Indexing
2. Iteration over the Groups
3. Dispatch Methods
4. Aggregation : aggregate(), filter(), transform()
5. apply() method
6. Specifying the split key : 
    * A list, array, series, or index providing the grouping keys
    * A dictionary or series mapping index to group. 
    * Any Python function. 
    * A list of valid keys
7. Grouping example : double groupby

In [ ]:
# for this lesson, we will use our planets dataset

# 1. Column indexing on groupby object
import seaborn as sns
planets = sns.load_dataset('planets')

print('DataFrame groupby object: ', planets.groupby('method'))
print('Series groupby object : ', planets.groupby('orbital_period')['orbital_period'])

DataFrame groupby object:  <pandas.api.typing.DataFrameGroupBy object at 0x11283ec50>
Series groupby object :  <pandas.api.typing.SeriesGroupBy object at 0x118a50b90>

In [12]:
""" 
Here we’ve selected a particular Series group from the original DataFrame group by
reference to its column name. As with the GroupBy object, no computation is done
until we call some aggregate on the object:
"""
print(planets.groupby('method').mean()['orbital_period'])

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [24]:
# 2. Iteration over groups. 

''' 
The GroupBy object supports direct iteration over the groups,
returning each group as a Series or DataFrame
'''

for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

In [32]:
# 3. Dispatch methods

'''
Through some Python class magic, any method not explicitly
implemented by the GroupBy object will be passed through and called on the groups,
whether they are DataFrame or Series objects. For example, you can use the
describe() method of DataFrames to perform a set of aggregations that describe each
group in the data:
'''
print(planets.groupby('method')['year'].describe())

                               count         mean       std     min      25%  \
method
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75

                                  50%      75%     max
method
Astrometry                     2011.5  2012.25  2013.0
Eclipse Timing Variations      2010.0  2011.00  2012.0
Imaging                        2009.0  2011.00  2013.0
Microlensing                   2010.0  2012.00  2013.0
Orbital Brightness Modulation  2011.0  2012.00  2013.0
Pulsar Timing                  1994.0  2003.00  2011.0
Pulsation Timing Variations    2007.0  2007.00  2007.0
Radial Velocity                2009.0  2011.00  2014.0
Transit                        2012.0  2013.00  2014.0
Transit Timing Variations      2012.5  2013.25  2014.0

Looking at this table helps us to better understand the data: for example, the vast majority of planets have been discovered by the Radial Velocity and Transit methods, though the latter only became common (due to new, more accurate telescopes) in the last decade. The newest methods seem to be Transit Timing Variation and Orbital Brightness Modulation, which were not used to discover a new planet until 2011.


This is just one example of the utility of dispatch methods. Notice that they are applied to each individual group, and the results are then combined within GroupBy and returned. Again, any valid DataFrame/Series method can be used on the corresponding GroupBy object, which allows for some very flexible and powerful operations!

In [42]:
# 4. Aggregate, filter, transform, apply

""" 
The preceding discussion focused on aggregation for the combine operation, but
there are more options available. In particular, GroupBy objects have aggregate(),
filter(), transform(), and apply() methods that efficiently implement a variety of
useful operations before combining the grouped data.


For the purpose of the following subsections, we’ll use this DataFrame :
"""
rng = np.random.RandomState(0)
df["data_2"] = rng.randint(0,10,6)
df.rename(columns={'data':'data_1'}, inplace=True)

In [ ]:
# 4A Aggregation
''' 
the aggregate() method allows for even more flexibility. It can take
a string, a function, or a list thereof, and compute all the aggregates at once
'''
print(df.groupby('key').aggregate(['min', np.median, max]))

    data_1            data_2
       min median max    min median max
key
A        0    1.5   3      3    4.0   5
B        1    2.5   4      0    3.5   7
C        2    3.5   5      3    6.0   9

In [46]:
"""
Another useful pattern is to pass a dictionary mapping column names to operations
to be applied on that column
"""
print(df.groupby('key').aggregate({'data_1' :'min', 
                                    'data_2' : 'max'}))

     data_1  data_2
key
A         0       5
B         1       7
C         2       9

In [50]:
## 4B. Filtering

""" 
A filtering operation allows you to drop data based on the group properties. 

The filter() function should return a Boolean value specifying whether the group
passes the filtering. Here because group A does not have a standard deviation greater
than 4, it is dropped from the result
"""

print('--' *20, 'filtered dataframe','--'*20)
print(df.groupby('key').filter(lambda x: x['data_2'].std() > 4))

print('--' *20, 'std value of raw dataframe','--'*20)
print(df.groupby('key').std())

---------------------------------------- filtered dataframe ----------------------------------------
  key  data_1  data_2
1   B       1       0
2   C       2       3
4   B       4       7
5   C       5       9
---------------------------------------- std value of raw dataframe ----------------------------------------
      data_1    data_2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

In [ ]:
## 4C. Transformation
''' 
While aggregation must return a reduced version of the data, 
transformation can return some transformed version of the full data to recombine. 
For such a transformation, the output is the same shape as the input. 
A common example is to center the data by subtracting the group-wise mean
'''

print('--' *20, 'transformed dataframe','--'*20)
print(df.groupby('key').transform(lambda x: x - x.mean())) #transfrom make the same shape as the original dataframe

print('--' *20, 'mean value of raw dataframe','--'*20)
print(df.groupby('key').mean())

---------------------------------------- transformed dataframe ----------------------------------------
   data_1  data_2
0    -1.5     1.0
1    -1.5    -3.5
2    -1.5    -3.0
3     1.5    -1.0
4     1.5     3.5
5     1.5     3.0
---------------------------------------- mean value of raw dataframe ----------------------------------------
     data_1  data_2
key
A       1.5     4.0
B       2.5     3.5
C       3.5     6.0

In [67]:
# 5. The apply() method

''' 
The apply() method lets you apply an arbitrary function to the
group results. The function should take a DataFrame, and return either a Pandas
object (e.g., DataFrame, Series) or a scalar; the combine operation will be tailored to
the type of output returned.
'''

def norm_by_data2 (x) :
    x['data_1'] /= x['data_2'].sum()
    return x

# apply the function to the groupby object
print('--' *20, 'applied dataframe','--'*20)
print(df.groupby('key').apply(norm_by_data2))

---------------------------------------- applied dataframe ----------------------------------------
         data_1  data_2
key
A   0  0.000000       5
    3  0.375000       3
B   1  0.142857       0
    4  0.571429       7
C   2  0.166667       3
    5  0.416667       9

In [68]:
## 6. Specifying the split key

""" 
In the simple examples presented before, we split the DataFrame on a single column
name. This is just one of many options by which the groups can be defined, and we’ll
go through some other options for group specification here
"""

### 6A. A list, array, series, or index providing the grouping keys

""" 
The key can be any series or list with a length matching that of the DataFrame
"""
L = [0, 1, 0, 1, 2, 0]
print(df.groupby(L).sum())

   key  data_1  data_2
0  ACC       7      17
1   BA       4       3
2    B       4       7

In [72]:
## 6B. A dictionary or series mapping index to group. 

''' 
Another method is to provide a dictionary 
that maps index values to the group keys
'''

df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant','C':'consonant'}
print(df2.groupby(mapping).sum()) # type: ignore

           data_1  data_2
key
consonant      12      19
vowel           3       8

In [80]:
## 6C. Any Python function.

''' 
Similar to mapping, you can pass any Python function that will
input the index value and output the group:
'''
print(df2.groupby(str.lower).mean())

     data_1  data_2
key
a       1.5     4.0
b       2.5     3.5
c       3.5     6.0

In [82]:
## 6D. A list of valid keys. 

''' 
Further, any of the preceding key choices can be combined to group on a multi-index
'''

mapping = {'A': 'vowel', 'B': 'consonant','C':'consonant'}
print(df2.groupby([mapping, str.lower]).mean())

               data_1  data_2
key       key
consonant b       2.5     3.5
          c       3.5     6.0
vowel     a       1.5     4.0

In [ ]:
# 7. Grouping example
''' 
As an example of this, in a couple lines of Python code we can put all these together
and count discovered planets by method and by decade
'''

decade = 10 * (planets['year']//10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
print(planets.groupby(['method', decade])['number'].sum().unstack().fillna(0))

decade                         1980s  1990s  2000s  2010s
method
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

## Pivot Tables

We have seen how the GroupBy abstraction lets us explore relationships within a dataset. A pivot table is a similar operation that is commonly seen in spreadsheets and other programs that operate on tabular data. The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides
a multidimensional summarization of the data. 

The difference between pivot tables and GroupBy can sometimes cause confusion; it helps me to think of **pivot tables as essentially a multidimensional version of GroupBy aggregation**. 

> Pivot Table : That is, you split-apply-combine, but both the split and the combine happen across not a one-dimensional index, but across a two-dimensional grid

In [1]:
''''
For the examples in this section, we’ll use the database of passengers on the Titanic,
available through the Seaborn library
'''

import seaborn as sns
titanic = sns.load_dataset('titanic')
print(titanic.shape)
print(titanic.head())

(891, 15)
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

### Pivot Tables by Hand

To start learning more about this data, we might begin by grouping it according to gender, survival status, or some combination thereof. If you have read the previous section, you might be tempted to apply a GroupBy operation—for example, let’s look at survival rate by gender

In [9]:
# pivoting titanic table
print(titanic.groupby('sex')[['survived']].mean())

        survived
sex
female  0.742038
male    0.188908

In [14]:
print(titanic.groupby(['sex','class'])[['survived']].mean().unstack())

        survived
class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

This gives us a better idea of how both gender and class affected survival, but the code is starting to look a bit garbled. While each step of this pipeline makes sense in light of the tools we’ve previously discussed, the long string of code is not particularly
easy to read or use. This two-dimensional GroupBy is common enough that Pandas includes a convenience routine, pivot_table, which succinctly handles this type of multidimensional aggregation

### Pivot Table Syntax

Here is the equivalent to the preceding operation using the pivot_table method of DataFrames

In [16]:
print(titanic.pivot_table('survived', index='sex', columns='class'))

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

#### Multilevel pivot tables

Just as in the GroupBy, the grouping in pivot tables can be specified with multiple levels, and via a number of options. For example, we might be interested in looking at age as a third dimension

In [28]:
# multilevel pivot table
age = pd.cut(titanic['age'], [0, 18, 80])
print(titanic.pivot_table('survived', index=['sex',age],columns='class')) # type: ignore

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [32]:
''' 
We can apply this same strategy when working with the columns as well; let’s add info
on the fare paid using pd.qcut to automatically compute quantiles
'''

fare = pd.qcut(titanic['fare'], 2)
print(titanic.pivot_table('survived', ['sex', age], [fare, 'class'])) # type: ignore

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First
sex    age
female (0, 18]               NaN  1.000000  0.714286          0.909091
       (18, 80]              NaN  0.880000  0.444444          0.972973
male   (0, 18]               NaN  0.000000  0.260870          0.800000
       (18, 80]              0.0  0.098039  0.125000          0.391304

fare
class              Second     Third
sex    age
female (0, 18]   1.000000  0.318182
       (18, 80]  0.914286  0.391304
male   (0, 18]   0.818182  0.178571
       (18, 80]  0.030303  0.192308

#### Additional pivot table options

The full call signature of the pivot_table method of DataFrames is as follows:

```python 
DataFrame.pivot_table(data, values=None, index=None, columns=None, 
                        aggfunc='mean', fill_value=None, margins=False,
                        dropna=True, margins_name='All') 
```

We’ve already seen examples of the first three arguments; here we’ll take a quick look at the remaining ones. Two of the options :

1. fill_value and dropna, have to do with missing data and are fairly straightforward; we will not show examples of them here.

2. The aggfunc keyword controls what type of aggregation is applied, which is a meanby default. GroupBy, the aggregation specification can be a string representing one of several common choices ('sum', 'mean', 'count', 'min', 'max', etc.) or a function that implements an aggregation (np.sum(), min(), sum(), etc.). Additionally, it can be specified as a dictionary mapping a column to any of the above desired options

In [63]:
# multiple aggregation function

print(titanic.pivot_table(index='sex', columns ='class', 
                          aggfunc=({'fare': 'mean', 'survived': 'sum'}))) # type: ignore

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

Notice also here that we’ve omitted the values keyword; when you’re specifying a mapping for aggfunc, this is determined automatically.

At times it’s useful to compute **totals** along each grouping. This can be done via **the margins keyword**

In [61]:
# show total rows and columns through margins keyword
print(titanic.pivot_table('survived',index='sex',columns='class',
                          margins=True)) # type: ignore

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [66]:
# multiple aggregation function with total rows and columns
# we should explicitly specify the values to aggregate
print(titanic.pivot_table(
    index='sex',
    columns='class',
    values=['fare', 'survived'],
    aggfunc={'fare': 'mean', 'survived': 'sum'},
    margins=True
))

              fare                                  survived                \
class        First     Second      Third        All    First Second  Third
sex
female  106.125798  21.970121  16.118810  44.479818     91.0   70.0   72.0
male     67.226127  19.741782  12.661633  25.523893     45.0   17.0   47.0
All      84.154687  20.662183  13.675550  32.204208    136.0   87.0  119.0


class   All
sex
female  233
male    109
All     342

## Vectorized String Operations

One strength of Python is its relative ease in handling and manipulating string data. Pandas builds on this and provides a comprehensive set of vectorized string operations that become an essential piece of the type of munging required when one is working with (read: cleaning up) real-world data.

### Introducing Pandas String Operations

We saw in previous sections how tools like NumPy and Pandas generalize arithmetic operations so that we can easily and quickly perform the same operation on many array elements

In [75]:
# simple arithmetic operations on numpy array
x = np.arange(1,7,1)
print(x)
print(x*4)

[1 2 3 4 5 6]
[ 4  8 12 16 20 24]

Pandas includes features to address both this need for vectorized string operations and for correctly handling missing data via the str attribute of Pandas Series and Index objects containing strings. So, for example, suppose we create a Pandas Series with this data

In [85]:
data = pd.Series(['peter', 'Paul', None, 'MARY', 'gUIDO'])

print(data.str.capitalize())

0    Peter
1     Paul
2      NaN
3     Mary
4    Guido
dtype: str

### Tables of Pandas String Methods

If you have a good understanding of string manipulation in Python, most of Pandas’ string syntax is intuitive enough that it’s probably sufficient to just list a table of available methods; we will start with that here, before diving deeper into a few of the subtleties

#### Methods similar to Python string methods

Nearly all Python’s built-in string methods are mirrored by a Pandas vectorized string method. Here is a list of Pandas str methods that mirror Python string methods

![pandas-strings-methods](../images/pandas-strings-methods.png)

In [2]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                    'Eric Idle', 'Terry Jones', 'Michael Palin'])

print('lower : ', monte.str.lower())

print('But some others return numbers:',monte.str.len())

lower :  0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: str
But some others return numbers: 0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [92]:
# Boolean values:
monte.str.startswith('T')

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [93]:
# still others return lists or other compound values for each element:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

#### Methods using regular expressions

In addition, there are several methods that accept regular expressions to examine the content of each string element, and follow some of the API conventions of Python’s built-in re module

![pandas-strings-expression-methods](../images/pandas-strings-expression-methods.png)

With these, you can do a wide range of interesting operations. For example, we can extract the first name from each by asking for a contiguous group of characters at the beginning of each element

In [9]:
monte.str.extract('([A-Za-z]+)')

         0
0   Graham
1     John
2    Terry
3     Eric
4    Terry
5  Michael

Or we can do something more complicated, like finding all names that start and end with a consonant, making use of the start-of-string (^) and end-of-string ($) regular expression characters

In [10]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

The ability to concisely apply regular expressions across Series or DataFrame entries opens up many possibilities for analysis and cleaning of data.

#### Miscellaneous methods
there are some miscellaneous methods that enable other convenient operations

![other-pandas-strings-methods](../images/other-pandas-strings-methods.png)

#### Vectorized item access and slicing

The get() and slice() operations, in particular, enable vectorized element access from each array. For example, we can get a slice of the first three characters of each array using str.slice(0, 3). Note that this behavior is also available through Python’s normal indexing syntax—for example, df.str.slice(0, 3) is equivalent to df.str[0:3]:

In [ ]:
# string slicing
# Indexing via df.str.get(i) and df.str[i] is similar
print('normal indexing: ', monte.str[0:3])

print('string slicing: ', monte.str.slice(0,3))

normal indexing:  0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: str
string slicing:  0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: str

In [24]:
''' 
These get() and slice() methods also let you access elements of arrays returned by
split(). For example, to extract the last name of each entry, we can combine
split() and get()
'''
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

#### Indicator variables

Another method that requires a bit of extra explanation is the get_dummies() method. This is useful when your data has a column containing some sort of coded indicator. For example, we might have a dataset that contains information in the form of codes, such as A=“born in America,” B=“born in the United Kingdom,” C=“likes cheese,” D=“likes spam"

In [26]:
full_monte = pd.DataFrame({'name': monte,
                            'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C',
                            'B|C|D']})
full_monte

             name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Michael Palin  B|C|D

In [31]:
# try get_dummies()
print(full_monte['info'].str.get_dummies('|'))

   A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

## Working with Time Series

Pandas was developed in the context of financial modeling, so as you might expect, it contains a fairly extensive set of tools for working with dates, times, and time-indexed data. Date and time data comes in a few flavors, which we will discuss here :

1. Time stamps reference particular moments in time (e.g., July 4th, 2015, at 7:00a.m.).

2. Time intervals and periods reference a length of time between a particular beginning and end point—for example, the year 2015. Periods usually reference a special case of time intervals in which each interval is of uniform length and does not overlap (e.g., 24 hour-long periods constituting days).

3. Time deltas or durations reference an exact length of time (e.g., a duration of 22.56 seconds)

### Dates and Times in Python

The Python world has a number of available representations of dates, times, deltas, and timespans. While the time series tools provided by Pandas tend to be the most useful for data science applications, it is helpful to see their relationship to other packages used in Python

#### Native Python dates and times: datetime and dateutil

Python’s basic objects for working with dates and times reside in the built-in date time module. Along with the third-party dateutil module, you can use it to quickly perform a host of useful functionalities on dates and times. For example, you can manually build a date using the datetime type

In [10]:
from datetime import datetime

datetime(year=2026, month=6, day=1)

# Or, using the dateutil module, you can parse dates from a variety of string formats

from dateutil import parser
date = parser.parse("6th of July, 2026")
date

datetime.datetime(2026, 7, 6, 0, 0)

In [15]:
# Once you have a datetime object, 
# you can do things like printing the day of the week

date.strftime('%A')

'Monday'

A related package to be aware of is pytz, which contains tools for working with the most migraine-inducing piece of time series data: time zones.

The power of datetime and dateutil lies in their flexibility and easy syntax: you can use these objects and their built-in methods to easily perform nearly any operation you might be interested in. Where they break down is when you wish to work with large arrays of dates and times: just as lists of Python numerical variables are suboptimal compared to NumPy-style typed numerical arrays, lists of Python datetime objects are suboptimal compared to typed arrays of encoded dates.

In [18]:
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [23]:
''' 
Once we have this date formatted, however, 
we can quickly do vectorized operations
on it
'''

date + np.arange(16)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15',
       '2015-07-16', '2015-07-17', '2015-07-18', '2015-07-19'],
      dtype='datetime64[D]')

Because of the uniform type in NumPy datetime64 arrays, this type of operation can be accomplished much more quickly than if we were working directly with Python’s datetime objects, especially as arrays get large (we introduced this type of vectorization)

In [30]:
# on numpy date time, we can also format the date and time
print('raw :', np.datetime64('2026-06-04 12:00'))
print('formatted :',np.datetime64('2026-06-04 12:59:59.50', 'ns'))

raw : 2026-06-04T12:00
formatted : 2026-06-04T12:59:59.500000000

Notice that the time zone is automatically set to the local time on the computer executing the code. You can force any desired fundamental unit using one of many format codes; for example, here we’ll force a nanosecond-based time

![np-datetime-format-1](../images/np-datetime-format-1.png)
![np-datetime-format-2](../images/np-datetime-format-2.png)

For the types of data we see in the real world, a useful default is datetime64[ns], as it can encode a useful range of modern dates with a suitably fine precision. Finally, we will note that while the datetime64 data type addresses some of the deficiencies of the built-in Python datetime type, it lacks many of the convenient methods and functions provided by datetime and especially dateutil.

#### Dates and times in Pandas: Best of both worlds

[recommend to use]

Pandas builds upon all the tools just discussed to provide a Timestamp object, which **combines the ease of use of datetime and dateutil with the efficient storage and vectorized interface of numpy.datetime64**. 

From a group of these Timestamp objects, Pandas can construct a DatetimeIndex that can be used to index data in a Series or DataFrame; we’ll see many examples of this below.

In [32]:
# pandas datetime
date = pd.to_datetime("4th of July, 2015")
date

Timestamp('2015-07-04 00:00:00')

In [38]:
# we can also do date formating using python's datetime module or
# do vectorized operations using np.datetime64
# it's show that pandas date time more ease to use and powerful

print('pandas datetime format:',date.strftime('%A'))

print('pandas datetime vectorized operation:',date + pd.to_timedelta(np.arange(12), 'D'))

pandas datetime format: Saturday
pandas datetime vectorized operation: DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
              dtype='datetime64[us]', freq=None)

### Pandas Time Series: Indexing by Time

Where the Pandas time series tools really become useful is when you begin to index data by timestamps. For example, we can construct a Series object that has time-indexed data:

In [42]:
# use pandas datetime as index on dataframe

index = pd.DatetimeIndex(['2014-07-04', '2014-08-04',
                            '2015-07-04', '2015-08-04'])
data = pd.Series([0,1,2,3,], index=index)
print(data)

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [49]:
''' 
Now that we have this data in a Series, we can make use of 
any of the Series indexing patterns we discussed in previous sections, 
passing values that can be coerced into dates
'''
# slicing
print('slicing : \n',data['2014-07-04':'2015-07-04'])

# special date-only indexing operations, 
# such as passing a year to obtain a slice of all data from that year
print('\n')
print('special date-index slicing : \n', data['2014'])

slicing :
 2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64


special date-index slicing :
 2014-07-04    0
2014-08-04    1
dtype: int64

### Pandas Time Series Data Structures

This section will introduce the fundamental Pandas data structures for working with time series data :

* For time stamps, Pandas provides the Timestamp type. As mentioned before, it is essentially a replacement for Python’s native datetime, but is based on the more efficient numpy.datetime64 data type. The associated index structure is DatetimeIndex.

* For time periods, Pandas provides the Period type. This encodes a fixed frequency interval based on numpy.datetime64. The associated index structure is PeriodIndex.

* For time deltas or durations, Pandas provides the Timedelta type. Timedelta is a more efficient replacement for Python’s native datetime.timedelta type, and is based on numpy.timedelta64. The associated index structure is TimedeltaIndex.