In [3]:
# all library and packages used in this notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Manipulation with Pandas

Pandas is a newer package built on top of NumPy, and provides an efficient implementation of a DataFrame. **DataFrames are essentially multidimensional arrays with attached row and column labels**, and often with heterogeneous types and/or missing data. 

As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

As we saw, NumPy’s ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks. **its limitations become clear when :**

1. when we need more flexibility (attaching labels to data, working with missing data, etc.)
2. when attempting operations that do not map well to element-wise broadcasting (groupings, pivots,etc.)

## Introducing Pandas Objects

### The Pandas Series Object

A Pandas Series is a **one-dimensional array** of indexed data. **It can be created from a list or array**

In [14]:
# pandas series object
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data.index
data.index.values # show values of pandas object

array([0, 1, 2, 3])

In [ ]:
"""
Like with a NumPy array, data can be accessed by the associated index via the familiar
Python square-bracket notation
"""
data[0] # output : np.float64(0.25)
data[:2]

0    0.25
1    0.50
dtype: float64

#### Series as generalized NumPy array

From what we’ve seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. 

The essential difference is the presence of the index: 

 - while the NumPy array has an implicitly defined integer index used
to access the values
- the Pandas Series has an explicitly defined index associated with the values

    - This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. **if we wish, we can use strings as an index**

In [29]:
# create pandas object with non integer as index

data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                index = ('a','b','c','d'))

data.index.values # output : <StringArray>['a', 'b', 'c', 'd'] Length: 4, dtype: str
print(data)
print("--"*20)
# And the item access works as expected
data['b']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
----------------------------------------

np.float64(0.5)

#### Series as specialized dictionary

In this way, you can think of a Pandas Series a bit like a specialization of a Python dictionary. **A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values**

In [33]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [35]:
# Unlike a dictionary, though, the Series also supports array-style operations such as slicing

population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

#### Constructing Series objects

We’ve already seen a few ways of constructing a Pandas Series from scratch. where index is an optional argument, and data can be one of many entities.

to wrap up, while constructing pandas series : 
* data can be a list or NumPy array
* data can be a scalar, which is repeated to fill the specified index
* data can be a dictionary, in which index defaults to the sorted dictionary keys
* the index can be explicitly set if a different result is preferred, in this case the Series is populated only with the explicitly identified keys.

In [49]:
# pandas series object with list or numpy array
data = pd.Series(np.array([0.25, 0.5, 0.75, 1.0])) # numpy array
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with scalar value
data = pd.Series(5, index = ('100','200','300'))
print('constructed by numpy array : \n', data)
print("--"*20)

# pandas series object with dictionary
data = pd.Series({2:'a', 1:'b', 3:'c'})
print('constructed by dictionary : \n', data)
print("--"*20)

# pandas series object with explicit index
data = pd.Series({2:'a', 1:'b', 3:'c'}, index = [3,1])
print('constructed by dictionary with explicit index : \n', data)
print("--"*20)

constructed by numpy array :
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
----------------------------------------
constructed by numpy array :
 100    5
200    5
300    5
dtype: int64
----------------------------------------
constructed by dictionary :
 2    a
1    b
3    c
dtype: str
----------------------------------------
constructed by dictionary with explicit index :
 3    c
1    b
dtype: str
----------------------------------------

### The Pandas DataFrame Object

The next fundamental structure in Pandas is the DataFrame. Like the Series object discussed in the previous section, **the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary**

#### DataFrame as a generalized NumPy array

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. 

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, **you can think of a DataFrame as a sequence of aligned Series objects. Here, by “aligned” we mean that they share the same index**

In [53]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)

states = pd.DataFrame({'population' : population,
                        'area' : area})

states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [54]:
'''
Like the Series object, the DataFrame has an index attribute that gives access to the
index labels
'''

print('states index : ', states.index)
print('--'*20)

'''
Additionally, the DataFrame has a columns attribute, which is an Index object holding 
the column labels
'''

print('states columns : ', states.columns)
print('--'*20)

states index :  Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')
----------------------------------------
states columns :  Index(['population', 'area'], dtype='str')
----------------------------------------

#### DataFrame as specialized dictionary

we can also think of a DataFrame as a specialization of a dictionary. Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.

> asking for the 'area' attribute returns the Series object containing the areas

In [64]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional NumPy array, data[0] will return the first row. For a DataFrame, data['col0'] will return the first column. 

Because of this, it is probably better to think about **DataFrames as generalized dictionaries** rather than *generalized arrays*

#### Constructing DataFrame objects

##### From a single Series object. 
A DataFrame is a collection of Series objects, and a single column DataFrame can be constructed from a single Series

In [66]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

##### From a list of dicts 
Any list of dictionaries can be made into a DataFrame. We’ll use a simple list comprehension to create some data

In [ ]:
data = pd.DataFrame({'a' :i,
                    'b' : i+1} for i in range(10,13)
                    )
                    
data

    a   b
0  10  11
1  11  12
2  12  13

In [74]:
'''
Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
“not a number”) values
'''

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

##### From a dictionary of Series objects

As we saw before, a DataFrame can be constructed from a dictionary of Series objects

In [75]:
pd.DataFrame({'population': population,
                'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

##### From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names. If omitted, an integer index will be used for each

In [ ]:
pd.DataFrame(np.random.rand(3, 2), # 3 as rows and 2 as cols
            columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

        foo       bar
a  0.976408  0.029823
b  0.009230  0.007841
c  0.691969  0.326241

##### From a NumPy structured array

A Pandas DataFrame operates much like a structured array, and can be created directly from one

In [81]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')]) # numpy structured array
print ('A :', A)
print('--'*20)

pd.DataFrame(A)

A : [(0, 0.) (0, 0.) (0, 0.)]
----------------------------------------

   A    B
0  0  0.0
1  0  0.0
2  0  0.0